### ISSUE TITLE
windows10,php 7.4开启swow拓展，composer有点小问题

### ISSUE THREAD

**Issue by lobtao** [swow/swow#100]
windows10,php 7.4开启swow拓展 (v0.1.0-nightly20210910版本)
composer create-project hyperf/swow-skeleton 
composer创建项目会有小问题，慢，且常报curl错误，关闭swow.dll拓展，composer使用正常。
然后再开启swow，可正常使用swow的hyperf

**Comment by dixyes** [comment]
7.4的curl支持怕不是还有点毛病
（资源类型支持问题） 建议更新到8.0+

php7的支持将被抛弃，你可以试下最后一个支持7的提交 f183d99f5aaf3561f9f5e25ca83438fa2a442ed4 可能会修复这个问题

**Comment by justin-mc-lai** [comment]
相同的拓展，我使用的php8.0，创建hyperf一样的curl error

PS D:\Phpcode> composer create-project hyperf/swow-skeleton
Creating a "hyperf/swow-skeleton" project at "./swow-skeleton"
https://mirrors.aliyun.com/composer could not be fully loaded (cURL error: 2 (CURLM_BAD_EASY_HANDLE): cURL message: An easy handle was not good/valid. It could mean that it isn't an easy handle at all, or possibly that the handle already is in used by this or another multi handle.), package information was loaded from the local cache and may be out of date


  [RuntimeException]
  cURL error: 2 (CURLM_BAD_EASY_HANDLE): cURL message: An easy handle was not good/valid. It could mean that it isn't
   an easy handle at all, or possibly that the handle already is in used by this or another multi handle.


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]

![image](https://user-images.githubusercontent.com/13780920/148501266-95100b98-f839-460c-bfd9-6b922165db75.png)

**Comment by dixyes** [comment]
没有在我的测试环境复现 我估摸着是 #65 #68 这种经典curl问题

curl扩展的windows发布将curl静态编译进了php_curl.dll 而且

1. curl一直在更新，每个curl小版本的内部abi不一定稳定
2. php官方构建每个小版本都会更新到最新的curl
3. 所以你使用的的php_curl.dll可能是随8.0.14提供的，它静态连接到curl 7.76.1
4. 你使用的swow是202109010构建的，它使用的curl是8.0.11提供的curl 7.75.1

他们的内部abi不相同导致这个问题， 对于这个问题我们考虑这样的解决方法：

1. 用户使用最新的curl和php进行构建，但windows下[构建扩展](https://wiki.s-wow.com/#/zh-cn/install?id=%e7%bc%96%e8%af%91%e5%ae%89%e8%a3%85-windows)还是比较脑阔疼
2. 将curl代码完整重新实现 不再依赖php_curl.dll，这样就就不需要保证小版本兼容性（在做了 在做了）

**Comment by AuroraYolo** [comment]
要重新实现一套curl？

**Comment by dixyes** [comment]
> 要重新实现一套curl？

重（fu）新（zhi）实（zhan）现（tie）一下

将curl扩展的代码复制粘贴过来，方便修改，避免冲突，类似stream plainwrapper的操作： 现在的hook模式是替换了关键函数而非完整的从头到尾都处理了，这导致swow的二进制必须和php的版本完全一致。

**Comment by codingheping** [comment]
ctrl+c ctrl+v

**Comment by dixyes** [comment]
Closed, see FAQ: https://github.com/swow/swow/discussions/116
