### ISSUE TITLE
swow在win7 64位 php 8.x 下，加载错误，win10 64位 没问题

### ISSUE THREAD

**Issue by javacty** [swow/swow#107]
希望能兼容下win7 64位系统，谢谢！

**Comment by dixyes** [comment]
见 https://github.com/libuv/libuv/blob/v1.x/SUPPORTED_PLATFORMS.md

swow依赖libcat异步引擎 libcat使用了libuv作为底层 libuv已经抛弃win7支持

如果你认为这是一个bug（你认为libuv可能支持win7但它不官方表示支持） 你需要提供具体信息而非 “swow在win7 64位 php 8.x 下，加载错误”
