### ISSUE TITLE
[bug] channel pop execution does not respond

### ISSUE THREAD

**Issue by cexll** [swow/swow#113]
**Describe the bug / 问题描述**

在向channel->push后使用pop取出数据程序疑似无响应
**To Reproduce / 如何复现**

![image](https://user-images.githubusercontent.com/26520956/161695293-00081f13-682f-4302-8a41-d62946849382.png)

1. ws收到信息后将message push到channel
![image](https://user-images.githubusercontent.com/26520956/161695416-74a8ee5f-1197-4216-b194-b52e8abaf698.png)

2. 然后在service取出数据走到pop后程序疑似无响应了 拿不到数据 也不执行之后的代码 同时其他无异常例如 http 继续发送信息无异常

**Expected behavior / 正确的行为**

正确取出pop数据发送给ws客户端
![image](https://user-images.githubusercontent.com/26520956/161695722-78566642-3269-440a-9ede-8d0b4cf4bbc4.png)

**Outputs / 程序输出**

![image](https://user-images.githubusercontent.com/26520956/161695760-12858a6f-7e8a-4efc-851f-e63d54bdfe63.png)

**Runtime Environment / 运行环境**

OS:
```
Linux LAPTOP-9EPBATCU 4.4.0-22000-Microsoft #1-Microsoft Fri Jun 04 16:28:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```plain
fill here with your OS version / 在这填入你的OS信息
```
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

PHP: 
```
PHP 8.0.15 (cli) (built: Feb 11 2022 16:08:55) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.15, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.15, Copyright (c), by Zend Technologies
    with Yasd v0.3.9-alpha, Our Copyright, by codinghuang

```

Swow: 
```

Swow

Status => enabled
Author => Swow Team
Link => https://github.com/swow/swow
Contact => Twosee <twosee@php.net>
Version => 0.1.0-487abd24 ( NTS )
Built => Apr  3 2022 11:44:04
Context => boost-context
Scheduler => libuv-event
With => OpenSSL 1.1.1f  31 Mar 2020, cURL 7.68.0

```
**Additional context / 补充说明**

**Comment by cexll** [comment]
提供可运行demo
https://github.com/cexll/mixphp-swow-demo

**Comment by twose** [comment]
@cexll  Framework这个文件夹是空的，跑不了

**Comment by cexll** [comment]
可以不用他

**Comment by twose** [comment]
还没有仔细看 说一个可能的问题 Swow的运行模式类似于Golang，如果在主协程的末尾没有进行wait，主协程会退出并kill所有子协程，所以需要确认下你是否在主协程的末尾wait了，可以用Channel，或者Swow也提供了`Sync\waitAll()`方法，当然更推荐用Channel，可以通过对Channel的操作来决定何时退出进程。

**Comment by cexll** [comment]
好 明天我在研究研究 并提供最小可运行代码

**Comment by cexll** [comment]
然后我用了swow/channel 

https://github.com/cexll/mix-framework 
这是framework的代码 实际上是不需要的在composer删掉就可以 ![image](https://user-images.githubusercontent.com/26520956/161781905-9b1e2750-9e4a-4616-b014-ff387c0de33a.png)

**Comment by cexll** [comment]
![image](https://user-images.githubusercontent.com/26520956/161782311-2d1b750b-587a-4de5-82f4-72f5b71ef8ea.png)
这里使用了waitAll

**Comment by cexll** [comment]
明天我在确定一下 辛苦了大佬

**Comment by cexll** [comment]
demo已更新 主要运行文件在 `bin/swow.php` 处理逻辑在 `src/Service/Session.php`

https://github.com/cexll/mixphp-swow-demo

**Comment by twose** [comment]
...晕倒，你这个Session都没有start，都没有启动那个消费的协程，我改了一下是正常的
<img width="873" alt="image" src="https://user-images.githubusercontent.com/25978241/161883269-8faae9eb-1d72-4aba-8f61-cd86d4f5ecc2.png">

**Comment by twose** [comment]
BTW，在启动文件里加一行`\Swow\Debug\showExecutedSourceLines(true)`，就可以看到你程序的整个运行流程了

<img width="729" alt="image" src="https://user-images.githubusercontent.com/25978241/161883567-14c386c4-a1f4-42b7-b630-9a4217f830da.png">

![image](https://user-images.githubusercontent.com/25978241/161883551-dc21679f-fd26-479d-968d-b8b73d2129f0.png)

**Comment by cexll** [comment]
😲 可能后面改的时候改掉了

**Comment by cexll** [comment]
> 😲 可能后面改的时候改掉了

我在看一下 谢谢大佬

**Comment by cexll** [comment]
问题已解决 感谢大佬❤
