### ISSUE TITLE
希望编译扩展的时候，可以把php也静态编译

### ISSUE THREAD

**Issue by ikilobyte** [swow/swow#119]
cli模式下更希望是可以像`node`、`golang`那样纯静态编译，带着有`swow`扩展的纯静态编译php-cli，发送给其它的机器也能运行，而不需要在机器上安装php环境，虽然有docker，但一通操作下载，镜像大小也要上GB，不知道我这样表达的是否清楚，欢迎讨论

**Comment by ikilobyte** [comment]
cli运行模式也不需要php-fpm这种，然后可以自定义安装扩展到纯静态编译的`php-cli`，也可以改个名字就叫`swow`，以后运行的命令就是 `swow xxx.php start` ，更容器部署

**Comment by dixyes** [comment]
当然可以咯

Linux下：
```bash
# at php dir
git clone <this repo> ext/swow
./buildconf --force
./configure --disable-all --enable-swow --disable-shared --disable-cgi --disable-phpdbg --enable-cli
make EXTRA_LDFLAGS_PROGRAM=-all-static
# file will located at sapi/cli/php
```

Windows下有点麻烦 需要动构建系统，但也大同小异，可以参考micro的patches

macOS没办法构建静态二进制，需要在一个比较旧的os上用比较旧的xcode套件构建 （连接到一个古老的macOS libsystem库，然后让苹果处理兼容性问题）

also see micro: https://github.com/easysoft/phpmicro

**Comment by dixyes** [comment]
如果你在进行上述的linux操作时发生了swow相关的构建错误，那是swow构建系统的bug，请反馈

**Comment by ikilobyte** [comment]
好的，我试一下

**Comment by dixyes** [comment]
虽然但是linux上不建议这么做：

- 静态二进制么的pie 不清楚ASLR还好用不
- 么的libdl libffi直接去世 cli的`dl()`函数也去世了
- 二进制会很大（典型的带常用扩展的php要12M）

我倾向于把这样的二进制/micro用于可移植需求比较重要（比如要给满世界用各种奇奇怪怪发行版的客户部署）的场景

实现良好的docker镜像应该都能压到100M以下，对于那种只在固定的集群上跑的服务应该是完全够用了

**Comment by ikilobyte** [comment]
一般来说也不需要兼容很多机器，生产环境基本都是centos，ubuntu，至少我这边就是在ububtu上可用就ok，最近在寻找一些静态编译php的项目

**Comment by cexll** [comment]
> 一般来说也不需要兼容很多机器，生产环境基本都是centos，ubuntu，至少我这边就是在ububtu上可用就ok，最近在寻找一些静态编译php的项目

hi，静态编译项目有什么收获吗？
可以分享吗？

**Comment by ikilobyte** [comment]
> > 一般来说也不需要兼容很多机器，生产环境基本都是centos，ubuntu，至少我这边就是在ububtu上可用就ok，最近在寻找一些静态编译php的项目
> 
> hi，静态编译项目有什么收获吗？ 可以分享吗？

假设有以下场景
* 有10台服务器
* php-cli运行环境

当没有纯静态编译，且不使用docker，在一台服务器上配置好php运行环境后，这个配置好的php可执行文件是无法直接发送给其它服务器使用的，在这种情况下，剩下的9台服务器还得继续配置php环境，虽然有脚本(LNMP)，或者使用docker解决这个环境的问题，但我们通常会增加一些扩展到php，加上这些扩展后，镜像变得很大，臃肿

使用纯静态编译后，这个`php`可执行文件可以加入你想要的扩展，如`redis`、`swow`等等等，而且只有几十MB的大小，可直接发给剩下的9台服务器使用，或者打包成镜像，镜像体积更小，这种方式更适合容器部署，不知道我这样的表述能否讲明白

**Comment by cexll** [comment]
> > > 一般来说也不需要兼容很多机器，生产环境基本都是centos，ubuntu，至少我这边就是在ububtu上可用就ok，最近在寻找一些静态编译php的项目
> > 
> > 
> > hi，静态编译项目有什么收获吗？ 可以分享吗？
> 
> 假设有以下场景
> 
> * 有10台服务器
> * php-cli运行环境
> 
> 当没有纯静态编译，且不使用docker，在一台服务器上配置好php运行环境后，这个配置好的php可执行文件是无法直接发送给其它服务器使用的，在这种情况下，剩下的9台服务器还得继续配置php环境，虽然有脚本(LNMP)，或者使用docker解决这个环境的问题，但我们通常会增加一些扩展到php，加上这些扩展后，镜像变得很大，臃肿
> 
> 使用纯静态编译后，这个`php`可执行文件可以加入你想要的扩展，如`redis`、`swow`等等等，而且只有几十MB的大小，可直接发给剩下的9台服务器使用，或者打包成镜像，镜像体积更小，这种方式更适合容器部署，不知道我这样的表述能否讲明白

这些我清楚,我想了解你找到解决方案了吗 
swoole那个swoole-cli倒是一个方案

**Comment by ikilobyte** [comment]
> > > > 一般来说也不需要兼容很多机器，生产环境基本都是centos，ubuntu，至少我这边就是在ububtu上可用就ok，最近在寻找一些静态编译php的项目
> > > 
> > > 
> > > hi，静态编译项目有什么收获吗？ 可以分享吗？
> > 
> > 
> > 假设有以下场景
> > 
> > * 有10台服务器
> > * php-cli运行环境
> > 
> > 当没有纯静态编译，且不使用docker，在一台服务器上配置好php运行环境后，这个配置好的php可执行文件是无法直接发送给其它服务器使用的，在这种情况下，剩下的9台服务器还得继续配置php环境，虽然有脚本(LNMP)，或者使用docker解决这个环境的问题，但我们通常会增加一些扩展到php，加上这些扩展后，镜像变得很大，臃肿
> > 使用纯静态编译后，这个`php`可执行文件可以加入你想要的扩展，如`redis`、`swow`等等等，而且只有几十MB的大小，可直接发给剩下的9台服务器使用，或者打包成镜像，镜像体积更小，这种方式更适合容器部署，不知道我这样的表述能否讲明白
> 
> 这些我清楚,我想了解你找到解决方案了吗 swoole那个swoole-cli倒是一个方案

找到了一个，是我想要的，https://github.com/crazywhalecc/static-php-cli

**Comment by cexll** [comment]
> > > > > 一般来说也不需要兼容很多机器，生产环境基本都是centos，ubuntu，至少我这边就是在ububtu上可用就ok，最近在寻找一些静态编译php的项目
> > > > 
> > > > 
> > > > hi，静态编译项目有什么收获吗？ 可以分享吗？
> > > 
> > > 
> > > 假设有以下场景
> > > 
> > > * 有10台服务器
> > > * php-cli运行环境
> > > 
> > > 当没有纯静态编译，且不使用docker，在一台服务器上配置好php运行环境后，这个配置好的php可执行文件是无法直接发送给其它服务器使用的，在这种情况下，剩下的9台服务器还得继续配置php环境，虽然有脚本(LNMP)，或者使用docker解决这个环境的问题，但我们通常会增加一些扩展到php，加上这些扩展后，镜像变得很大，臃肿
> > > 使用纯静态编译后，这个`php`可执行文件可以加入你想要的扩展，如`redis`、`swow`等等等，而且只有几十MB的大小，可直接发给剩下的9台服务器使用，或者打包成镜像，镜像体积更小，这种方式更适合容器部署，不知道我这样的表述能否讲明白
> > 
> > 
> > 这些我清楚,我想了解你找到解决方案了吗 swoole那个swoole-cli倒是一个方案
> 
> 找到了一个，是我想要的，https://github.com/crazywhalecc/static-php-cli

我一会看看 谢咯 研究研究

**Comment by crazywhalecc** [comment]
本项目 static-php-cli 我测试了下，可以正确将 swow 静态编译进去的。只是 Http Server example 我无法运行，但是 TCP Server 可以正常运行。

<img width="1161" alt="err" src="https://user-images.githubusercontent.com/20330940/168619355-4f97769f-9d2c-40c6-99a7-386f63d4d135.png">

**Comment by dixyes** [comment]
swow构建系统还是有点bug 昨天刚修： e7584dd8985aca50a77af33b720806123a2996ae

（micro昨天也刚修了对swow/swoole的fshook的兼容性： dixyes/phpmicro@49589bb5dae7ec8da230727d6339e57cc6d1390d

@crazywhalecc 对于glibc 建议在老centos上 构建所有依赖（--enable-static --disable-shared）然后用-static而不是-all-static构建， musl可以用musl wrapper在任意有musl wrapper的机器/镜像上构建

这样构建出来的二进制就是[PIE](https://zh.wikipedia.org/wiki/%E5%9C%B0%E5%9D%80%E6%97%A0%E5%85%B3%E4%BB%A3%E7%A0%81)了，完全支持[ASLR](https://zh.wikipedia.org/zh-hans/%E4%BD%8D%E5%9D%80%E7%A9%BA%E9%96%93%E9%85%8D%E7%BD%AE%E9%9A%A8%E6%A9%9F%E8%BC%89%E5%85%A5)

我最近在给micro撸新的构建系统（原先那个写的太烂了），里面对依赖库的构建就这思路

（再加亿点点魔法就资瓷ffi了，但不能跨c库）

效果：

```shell
dixyes@somehost ~/lwmbs % file src/php-src/sapi/micro/micro.sfx
src/php-src/sapi/micro/micro.sfx: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, stripped
dixyes@somehost ~/lwmbs % /lib/ld-musl-x86_64.so.1 --list src/php-src/sapi/micro/micro.sfx
        /lib/ld-musl-x86_64.so.1 (0x7f42f051b000)
        libc.so.6 => /lib/ld-musl-x86_64.so.1 (0x7f42f051b000)
dixyes@somehost ~/lwmbs % cat ffiplay.php
<?php

$ffi = \FFI::cdef(<<<'CDEF'
int callee();
int callee2(int (*func)(int));
CDEF, './callee.so');

var_dump($ffi->callee());
var_dump($ffi->callee2(function ($in) {
    print("im callback input: $in\n");
    return $in * 7;
}));

dixyes@somehost ~/lwmbs % cat src/php-src/sapi/micro/micro.sfx enableffi.bin ffiplay.php > ffiplay.exe && chmod 0755 ffiplay.php
dixyes@somehost ~/lwmbs % cat callee.c

#include <stdio.h>

int callee() {
    printf("hello world!\n");
    return 42;
}

int callee2(int (*func)(int)) {
    int ret = func(6);
    printf("func(6) = %d\n", ret);
    return ret;
}
dixyes@somehost ~/lwmbs % musl-gcc -shared callee.c -o callee.so
dixyes@somehost ~/lwmbs % ./ffiplay.exe
hello world!
int(42)
im callback input: 6
func(6) = 42
int(42)
dixyes@somehost ~/lwmbs % gcc -shared callee.c -o callee.so
dixyes@somehost ~/lwmbs % ./ffiplay.exe
hello world!
int(42)
im callback input: 6
func(6) = 42
int(42)
dixyes@somehost ~/lwmbs % src/php-src/sapi/micro/tests/fakecmd.exe -m
[PHP Modules]
Core
date
openssl
pcre
ctype
curl
FFI
fileinfo
filter
hash
iconv
json
mbstring
SPL
session
parallel
pcntl
standard
mysqlnd
PDO
pdo_mysql
Phar
posix
redis
Reflection
mysqli
Swow
tokenizer
zip

[Zend Modules]
```

**Comment by dixyes** [comment]
micro新构建系统的构建脚本部分（lwmbs）做的差不多了

这里有一些构建好的二进制（生成测试的产物），带swow parallel redis curl和一些个其他常见扩展：
~~https://github.com/dixyes/lwmbs/actions/runs/2359538960~~

micro是指micro SAPI， cli就是php命令

shared是 **仅连接到C库的** 动态文件，他们

- 可以在任意同C库的发行版使用（例如shared_musl可以在alpine、openwrt上用）
- 需要考虑c库版本兼容性（例如shared_glibc链接到2.34则不能在2.34以前的系统用）
- 不需要考虑其他库的兼容性
- 可以dl（包括php dl()和ffi）
- 是PIE文件
- 不能不带c库运行（例如不能单文件作为init进程）

static是静态的，他们

- 可以在支持的linux内核上使用
- 不需要考虑任何库版本的兼容性
- 不可以dl（包括php dl()和ffi）
- 可以不带c库运行（可以单文件作为init进程）

lwmbs不推荐用户直接使用，它应该在docker内使用（在centos7连接到老glibc来避免glibc兼容性问题

可以尝试一下构建出来的两个php版本的4种风味的二进制是否能满足要求

（TODO: 完整的micro/cli构建系统

EDIT: update

linux:
https://github.com/dixyes/lwmbs/actions/runs/2370415766
macos: 
https://github.com/dixyes/lwmbs/actions/runs/2370415767

**Comment by cexll** [comment]
> micro新构建系统的构建脚本部分（lwmbs）做的差不多了
> 
> 这里有一些构建好的二进制（生成测试的产物），带swow parallel redis curl和一些个其他常见扩展： https://github.com/dixyes/lwmbs/actions/runs/2359538960
> 
> micro是指micro SAPI， cli就是php命令
> 
> shared是 **仅连接到C库的** 动态文件，他们
> 
> * 可以在任意同C库的发行版使用（例如shared_musl可以在alpine、openwrt上用）
> * 需要考虑c库版本兼容性（例如shared_glibc链接到2.34则不能在2.34以前的系统用）
> * 不需要考虑其他库的兼容性
> * 可以dl（包括php dl()和ffi）
> * 是PIE文件
> * 不能不带c库运行（例如不能单文件作为init进程）
> 
> static是静态的，他们
> 
> * 可以在支持的linux内核上使用
> * 不需要考虑任何库版本的兼容性
> * 不可以dl（包括php dl()和ffi）
> * 可以不带c库运行（可以单文件作为init进程）
> 
> lwmbs不推荐用户直接使用，它应该在docker内使用（在centos7连接到老glibc来避免glibc兼容性问题
> 
> 可以尝试一下构建出来的两个php版本的4种风味的二进制是否能满足要求
> 
> （TODO: 完整的micro/cli构建系统

牛逼~(破声

**Comment by dixyes** [comment]
Closed via https://github.com/crazywhalecc/static-php-cli
