### ISSUE TITLE
[bug] win7 64 位环境下PHP8.0加上swow扩展会报错 无法定位程序输入点GetHostNameW于动态链接库WS2_32.dll上

### ISSUE THREAD

**Issue by justasong** [swow/swow#125]
**Describe the bug / 问题描述**
win7 64 位环境下PHP8.0加上swow扩展会报错
报错内容是: 无法定位程序输入点GetHostNameW于动态链接库WS2_32.dll上
![image](https://user-images.githubusercontent.com/66345043/174741746-eb7f0af7-9ba7-4970-b80a-8dab3ad34b1d.png)

**To Reproduce / 如何复现**

1. 从php官方下载8.0的php包 https://windows.php.net/download#php-8.0
2. 下载对应swow release的php扩展
3. cd 到php包根目录：执行 `php-v` 就出现报错

**Expected behavior / 正确的行为**

无报错

**Outputs / 程序输出**

![image](https://user-images.githubusercontent.com/66345043/174742271-25c51225-c5a4-4730-85f2-01d271943f88.png)

**Runtime Environment / 运行环境**

OS:

```plain
Caption=Microsoft Windows 7 旗舰版
CSDVersion=Service Pack 1
OSArchitecture=64-bit
OSLanguage=2052
TotalVisibleMemorySize=4193784
Version=6.1.7601

Architecture=9
Caption=Intel64 Family 6 Model 85 Stepping 7
Name=Intel(R) Xeon(R) Gold 6238L CPU @ 2.10GHz
NumberOfCores=1
NumberOfLogicalProcessors=1


Architecture=9
Caption=Intel64 Family 6 Model 85 Stepping 7
Name=Intel(R) Xeon(R) Gold 6238L CPU @ 2.10GHz
NumberOfCores=1
NumberOfLogicalProcessors=1
```

PHP: 

Swow: 
PHP 8.0.20 (cli) (built: Jun  8 2022 09:10:24) ( NTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.20, Copyright (c) Zend Technologies

**Additional context / 补充说明**

扩展注释掉之后，就无报错了。应该跟扩展有关系

**Comment by dixyes** [comment]
Swow对操作系统的兼容性主要受到libuv的限制，见[libuv支持平台](https://github.com/libuv/libuv/blob/v1.x/SUPPORTED_PLATFORMS.md)。
简单来说：Linux>=2.6.32 macOS>=10.15 Windows>=8 FreeBSD>=10 NDK>=r15b (Android 7.0)

libuv不支持Windows7

理论上来说可以实现一堆兼容层来做这个事，然而显然libuv的开发者选择不支持，应该是实现上有巨大的困难，建议更新系统。

also see #116
