### ISSUE TITLE
Windows安装手动构建 swow dll 文档链接打不开

### ISSUE THREAD

**Issue by andy236726493** [swow/swow#129]
1.Windows安装
手动构建见[文档](https://wiki.s-wow.com/#/zh-cn/install?id=%e7%bc%96%e8%af%91%e5%ae%89%e8%a3%85-windows)
文档链接  打不开
2.官方  swow.dll   在哪里下

**Comment by dixyes** [comment]
1. 文档站域名过期了，过一段时间我们会重建一波文档站，暂且不可访问，如果你想看原文：https://github.com/swow/swow-wiki/blob/master/docs/zh-cn/install.md
2. 任何一个release都有： https://github.com/swow/swow/releases

**Comment by andy236726493** [comment]
看到了，谢谢。
另外有个问题，请教一下，Windows 环境 nginx 下 ，  hyperf  使用swow 驱动， 能用  PHP-FPM吗

**Comment by dixyes** [comment]
> 看到了，谢谢。 另外有个问题，请教一下，Windows 环境 nginx 下 ， hyperf 使用swow 驱动， 能用 PHP-FPM吗

你都用hyperf了，为啥要fpm啊，nginx直接proxy_pass啊

**Comment by andy236726493** [comment]
windows x下用PHP-FPM  开发，不需要每次修改代码后热更新，开发效率更高，  生产时用 linux   nginx直接proxy_passi

**Comment by andy236726493** [comment]
如果indows下能用PHP-FPM 开发，最好了
