### ISSUE TITLE
为什么不用ffi呢？

### ISSUE THREAD

**Issue by hanhyu** [swow/swow#14]
为什么不直接使用php7.4以上的FFI直接调用，这样就可以完全用composer安装了。

**Comment by Littlesqx** [comment]
个人认为，性能没有 PECL 好，而且 FFI 还挺新的吧，估计需要踩坑，最重要的，最低要求 7.4 不友好。

还可能 ffi 的权限有限（没有扩展那么底层和支持很多 API

**Comment by limingxinleo** [comment]
Swow类似于opcache，你可以类比考虑一下ffi怎么做opcache。。。

就知道为啥不用ffi了
