### ISSUE TITLE
在windows10系统下会提示"无法定位程序输入点nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation于动态链接库php_swow.dll上"

### ISSUE THREAD

**Issue by systoms** [swow/swow#149]
在windows10系统下会提示"无法定位程序输入点nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation于动态链接库php_swow.dll上"

操作系统: windows10 64位操作系统
PHP: PHP 8.2.1 (cli) (built: Jan  3 2023 23:31:58) (ZTS Visual C++ 2019 x64)
Swow: php_swow-php8.2-x64-ts-VS16.dll

**Comment by twose** [comment]
Swow 还没有引入 nghttp2，这个报错有点奇怪，需要 @dixyes 协助确认下。

**Comment by dixyes** [comment]
构建问题

先用这里的8.2： https://github.com/dixyes/swow/releases/tag/v1.1.0-alpha-20230109

**Comment by systoms** [comment]
多谢
