### ISSUE TITLE
[bug] error: unknown type name 'CAT_BUFFER_STR_FREE'

### ISSUE THREAD

**Issue by pizsd** [swow/swow#152]
**Describe the bug / 问题描述**
编译安装时，执行make命令出现错误

In file included from src/swow_socket.c:19:
In file included from /Users/home/php/swow/ext/include/swow_socket.h:27:
/Users/home/php/swow/ext/deps/libcat/include/cat_socket.h:193:9: error: unknown type name 'CAT_BUFFER_STR_FREE'
CAT_API CAT_BUFFER_STR_FREE char *cat_socket_write_vector_str(const cat_socket_write_vector_t *vector, unsigned int vector_count);
        ^
1 error generated.
make: *** [src/swow_socket.lo] Error 1

**To Reproduce / 如何复现**

1. 下载包
2. cd swow/ext
3. phpize
4. ./configure
5. make

**Expected behavior / 正确的行为**

**Outputs / 程序输出**

**Runtime Environment / 运行环境**
Darwin MacBook-Pro-91.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
OS:

```plain
macOS 10.15.7
```

PHP 8.1.3 (cli) (built: Mar  1 2022 01:17:32) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.3, Copyright (c), by Zend Technologie

curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
openssl@1.1

**Comment by twose** [comment]
Fixed in [83cf007](https://github.com/swow/swow/commit/83cf0070811de87027c097438d900ff4c77842a0)

Thanks for your feedback!
