### ISSUE TITLE
[discussion] 建议 socket 支持sendfile

### ISSUE THREAD

**Issue by smallslime** [swow/swow#161]
如题

零拷贝，有时候开发中需要简单的小文件下载，有这个就方便多了

**Comment by twose** [comment]
计划中的，但需要注意的是 sendfile 在 SSL 连接上不可行，自己分片发送可能是兼容性更好的方案，但不排除底层会自动使用分片发送来实现 sendfile 。

**Comment by smallslime** [comment]
感谢大佬回复。很喜欢swow的理念，祝发展越来越好！

**Comment by twose** [comment]
已支持，包含在 v1.2.0 中。
（注，尚未封装 HTTP 版本的 sendHttpFile（计划在下个版本支持），目前提供的是原始的 socket sendFile 调用。可以通过先 send(packHttpResponse(...)) + sendFile 两次调用的方法来实现。
