### ISSUE TITLE
[discussion] 请问有没有ide help，在vscode下能看到代码提示的。

### ISSUE THREAD

**Issue by 529124368** [swow/swow#164]

**Comment by xywf221** [comment]
你可以按照文档composer引用下 vscode就会提示了

**Comment by 529124368** [comment]
@xywf221 
感谢啊，我直接下载的win版的dll，没注意composer。 
composer 拉了一下swow，就可以了。

**Comment by windqyoung** [comment]
有兴趣可以用这个包 生成提示。

https://packagist.org/packages/windqyoung/ide-helper

另外提个建议，可不可以在 类，方法 的doc_comment上多写一些示例说明，反射出来能看。大部分方法都能望名知意。有少数一些看不懂用法。
