### ISSUE TITLE
window10安装不了扩展

### ISSUE THREAD

**Issue by lushaobo** [swow/swow#166]
我目前的php版本
![图片](https://user-images.githubusercontent.com/5574978/221351067-8666de4e-a902-4de9-b944-059bff695e6d.png)

下载的扩展包为：
php_swow-php8.1-x64-nts-VS16.dll 

当我添加 extension=swow 到 php.ini 时，执行 php -m 命令则所有扩展都显示不了

![图片](https://user-images.githubusercontent.com/5574978/221351299-1b1cb44a-c760-41bb-a9c8-b0f9f4463983.png)

第一次安装，不太了解。如果哪里操作出错，麻烦说下。

**Comment by xywf221** [comment]
额你这个报错是完全不能看清楚什么原因，你先把命令行的编码设置成utf-8再发下报错信息吧

**Comment by lushaobo** [comment]
目前已经解决，是我这边的问题。
主要问题是这样的， php.ini 里面 `extension=swow` 这个配置，要放到其它扩展后面，如果放到最前面，则 php -m 没有任何反映。

另外， 打印 phpinfo() 的时候，发现是没有打印 swow 相关信息出来。要在命令行执行  php --ri swow 才会显示。（可能跟 phpinfo 是通过 php-fpm 调用的有关吧，具体不太清楚。）

**Comment by xywf221** [comment]
如果phpinfo没相关信息检查下 cli 模式用到的ini文件跟 fpm用到的ini是否一致

**Comment by lushaobo** [comment]
phpinfo 不显示 swow 的问题解决了，原先的 php-fpm 由于配置出错，所以重启不生效，现在重启电脑就正常了。

现在没问题了，能正常使用 swow了，今天的问题主要是我这边， extension=swow 这条配置没放对位置（需要放到所有加载扩展配置的最后，可能是有依赖关系存在）。

最后祝 swow 越办越好 ！！！（之前不使用swoole开发项目是因为不兼容windows开发，现在swow满足了这个需求。）
