### ISSUE TITLE
请问有协程版本的mysql开发计划吗

### ISSUE THREAD

**Issue by duxphp** [swow/swow#177]
Swoole 是进行重写驱动适配的，Swow是否有计划开发，还是有其他方法可以支持？

**Comment by twose** [comment]
啥啊，直接用 PDO 或者 mysqli 就是协程化的，开了 Swow 扩展就自动 hook 的，不需要再搞一套。

**Comment by twose** [comment]
可以看看：[Swow：我是谁？我能做什么？](https://docs.toast.run/swow-blog/chs/init.html)

**Comment by duxphp** [comment]
是有点疑问，因为我在开发 Laravel orm 连接池时使用 Channel，对每个路由的请求使用 pop 获取新的链接，请求完成后 push 归连接池，但是并发请求下还但是会报错：

`
SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.
`

经过检查发现多个Url链接同时请求路由时为并发执行了 Sql 所以才有此疑惑，测试路由内的处理再次放置在协程内执行也同样的问题，并且尝试设置 MYSQL_ATTR_USE_BUFFERED_QUERY 依然无效果。

**Comment by twose** [comment]
看不懂，要么就是写的不对，要么就是放回连接池之前没有用 fetchAll() 回收完缓冲区里的所有数据。

**Comment by he426100** [comment]
看看Hyperf咋实现连接池的，或者think-swoole。
think-swoole连接池关键部分如下：
1. 重写createConnection，把数据库连接替换为数据库代理
2. 调用数据库方法的时候先从连接池获取连接，取出后放在协程上下文，每个顶级协程只取一次连接，后续从上下文获取。

看你的描述很奇怪，连接池应该只跟当前会话所在的协程相关，怎么扯上路由了？

**Comment by duxphp** [comment]
>

是这样的，实现代码是这样的 一个路由就是一个协程，在调用数据库也重写了数据库连接驱动使用了连接池代理new Pdo 然后在获取连接的时候放在上下文内，还是一样的问题，我再参考下其他的框架吧

`
$server = new Server();
        $server->bind('0.0.0.0', 8080)->listen();


        while (true) {
            try {
                $connection = $server->acceptConnection();
                Coroutine::run(static function () use ($connection): void {
                    try {
                        $request = null;
                        try {
                            $request = $connection->recvHttpRequest();
                            $response = App::app()->handle($request);
                            $connection->respond($response->getHeaders(), (string)$response->getBody(), $response->getStatusCode());
                        } catch (ProtocolException $exception) {
                            dump($exception->getCode() . ' : ' . $exception->getMessage());
                            $connection->error($exception->getCode(), $exception->getMessage(), close: true);
                        }
                    } catch (Exception $e) {
                        dump($e->getMessage());
                        // you can log error here
                    } finally {
                        DbPool::getInstance()->release();
                        $connection->close();
                    }
                });
            } catch (Exception $exception) {
                if (in_array($exception->getCode(), [Errno::EMFILE, Errno::ENFILE, Errno::ENOMEM], true)) {
                    sleep(1);
                } else {
                    dump($exception->getCode() . ' : ' . $exception->getMessage());
                    break;
                }
            }
        }
`
