### ISSUE TITLE
[bug] win版安装问题

### ISSUE THREAD

**Issue by cffycls** [swow/swow#179]
**Describe the bug / 问题描述**

https://github.com/swow/swow/releases/tag/v1.2.0

[php_swow-php8.2-x64-ts-VS16.dll](https://github.com/swow/swow/releases/download/v1.2.0/php_swow-php8.2-x64-ts-VS16.dll)
1.18 MB
last month
[php_swow-php8.2-x64-ts-VS16.pdb](https://github.com/swow/swow/releases/download/v1.2.0/php_swow-php8.2-x64-ts-VS16.pdb)
5.7 MB
last month

phpinfo:

-- | --
-- | --
System | Windows NT IDEAPAD 10.0 build 22621 (Windows 11) AMD64
Build Date | Mar 14 2023 17:50:26
Build System | Microsoft Windows Server 2019 Datacenter [10.0.17763]
Compiler | Visual C++ 2019
Architecture | x64
PHP API | 20220829
PHP Extension | 20220829
Zend Extension | 420220829
Zend Extension Build | API420220829,TS,VS16
PHP Extension Build | API20220829,TS,VS16
Debug Build | no
Thread Safety | enabled
Thread API | Windows Threads
Zend Signal Handling | disabled
Zend Memory Manager | enabled

下载并改名到ext目录：
php_swow.dll
php_swow.pdb 

php -m
ext\php_swow.dll doesn't appear to be a valid Zend extension

Swow: 

系统win11, php8.2.4

**Additional context / 补充说明**

**Comment by twose** [comment]
不要用 `zend_extension=swow`，应该用 `extension=swow`

**Comment by cffycls** [comment]
？啊，还真是
