### ISSUE TITLE
`recvHttpRequest` 是否需要 `timeout` 参数

### ISSUE THREAD

**Issue by xuanyanwow** [swow/swow#184]
- 复现方法：`hyperf/engine-swow`: https://github.com/hyperf/engine-swow/blob/master/src/Http/Server.php#L69
- 存在问题：`connection use keep-alive` 子协程永远不退出
- 需要对 keep-alive 连接 recvHttpRequest 做超时处理（60秒没有新请求 则close）
- 讨论：框架层实现[超时close协程]还是swow处理[超时抛出异常]  https://github.com/hyperf/engine-swow/blob/master/src/Http/Server.php#L69
- 相关的还有`keepalive_requests` 最大请求数量

**Comment by xuanyanwow** [comment]
猜想：假设不是keep-alive的请求，发送不完整的http内容，是否也会一直堵塞？

**Comment by twose** [comment]
> 猜想：假设不是keep-alive的请求，发送不完整的http内容，是否也会一直堵塞？

会，这个是已知的情况，所以要根据自己的需求对 $connection 设置超时。

> 需要对 keep-alive 连接 recvHttpRequest 做超时处理（60秒没有新请求 则close）

最简单的方式是设置 Socket 超时，如 `$connection->setReadTimeout(60_000)`；但这个只能控制到单个 recv 操作级别的超时，而不是整个 request 的超时，但越精细的控制就会带来越大的性能开销，其实并不划算，因为大多数时候我们不需要那么精确的超时，但是这种方法可能应对不了「逐字节的慢速 TCP 攻击」。
另一种方式是记录最后活跃时间，通过建立一个心跳监控协程，每 x 秒去遍历一下连接列表 （$server->getConnections()），切断不活跃的协程，这个时间的维度可以自己掌控。

> 框架层实现[超时close协程]还是swow处理[超时抛出异常] 

这些需求技术上都可以做，但 Swow 是一个最小核心，还是职能边界的问题。

@huanghantao 在我司内部用 Swow 实现了一个 API 网关，积累了很多经验，有空可以分享一下，其实上面的问题多少都有涉及，需要一个最佳实践。

**Comment by twose** [comment]
聊到慢速攻击，感觉确实有必要给 recv 类操作实现一个超时，只是会带来一些些额外开销和些许复杂性。

**Comment by zxyfaxcn** [comment]
这个问题困扰我一段时间了 @huanghantao

**Comment by xuanyanwow** [comment]
- https://github.com/swow/swow/commit/dd615e996be574a50913f53c3ead3221dccb6e2c
- https://github.com/swow/swow/commit/92478d07b0e45daa9c5f82215cd6b62b58e52cb4
