### ISSUE TITLE
安装完拓展后无法使用composer安装包

### ISSUE THREAD

**Issue by zsxl** [swow/swow#185]
composer错误信息： cURL error: 2 (CURLM_BAD_EASY_HANDLE): cURL message: An easy handle was not good/valid. It could mean that it isn't an easy handle at all, or possibly that the handle already is   
   in used by this or another multi handle. 

注释掉swow拓展恢复正常

**Comment by AuroraYolo** [comment]
执行的什么命令？

**Comment by zsxl** [comment]
> 执行的什么命令？

执行的composer require hyperf/validation，后面试了其他的包也是这个错误，windwos11

**Comment by xywf221** [comment]
提供下swow信息跟php版本

**Comment by zsxl** [comment]
> 提供下swow信息跟php版本
php版本是，phpstudy里面的 php8.0.2.nts
swow是这个：https://github.com/swow/swow/releases/download/v1.2.0/php_swow-php8.0-x64-nts-VS16.dll

**Comment by twose** [comment]
可能是 Swow 的 cURL 版本和 PHP 提供的 cURL 版本不一致

可以通过查看 `php --ri curl` 和 `php --ri swow` 来确认

具体需要怎么解决得问问 @dixyes

**Comment by dixyes** [comment]
目测多半是curl版本不匹配，可以考虑在它提供的版本上自行构建：  https://docs.toast.run/swow/chs/install.html
或者使用这个版本swow连接到的php： https://windows.php.net/downloads/releases/php-8.0.28-nts-Win32-vs16-x64.zip

**Comment by twose** [comment]
v1.5.0 已彻底解决。
