### ISSUE TITLE
[bug] php stream create tls server error

### ISSUE THREAD

**Issue by xywf221** [swow/swow#187]
下面代码php原生没有问题但是启用swow后会提示 `PHP Warning:  stream_socket_server(): Unable to connect to tls://127.0.0.1:1234 (Unknown error)`
```php
$socket = stream_socket_server("tls://127.0.0.1:1234", context: $context);
```
只能另辟蹊径使用
```php
$socket = stream_socket_server("tcp://127.0.0.1:1234", context: $context);
$connection = stream_socket_accept($socket)
stream_socket_enable_crypto($connection, true, STREAM_CRYPTO_METHOD_TLS_SERVER)
```

**Comment by twose** [comment]
代码写错了，可以换成 "ssl://" 解决，是一样的，下个版本修复

**Comment by lanlin** [comment]
天，这个问题困扰我太久了！

我是 redis tls 的问题。每次本地测试都没问题，一连线上就报 redis server went away。

找了好久定位到是 tls 的问题，只要开启 tls 就一定会报错。 

没有想过 swow 里面是可以写成 ssl:// 的，一直以为 swow 不支持 tls 1.1 1.2..

**Comment by twose** [comment]
> 天，这个问题困扰我太久了！
> 
> 我是 redis tls 的问题。每次本地测试都没问题，一连线上就报 redis server went away。
> 
> 找了好久定位到是 tls 的问题，只要开启 tls 就一定会报错。
> 
> 没有想过 swow 里面是可以写成 ssl:// 的，一直以为 swow 不支持 tls 1.1 1.2..

@lanlin  😂 你早点提 issue 我马上就修了
