### ISSUE TITLE
PHP slower after Swow installation

### ISSUE THREAD

**Issue by gilbertoalbino** [swow/swow#191]
Hi there!

I've just installed Swow following the instructions provided here, but got some weird results.

Before that I was able to run 30K requests/seconds in vanilla PHP-FPM.

After I was able to run only 10K requests/seconds in vanilla PHP-FPM or Swow example.

I am running PHP 8.1 agains Ubuntu 22.04.

Removing the extension I got back my 30k req/seconds (but of course can't use Swow anymore). 

So indeed the problem was this extension.

Just a dummy question: Am I missing something here since vanilla PHP is faster, why bother with this extension?

**Comment by dixyes** [comment]
Since swow/swoole is not designed for fpm, we have seldom tested on fpm, there might be some fpm-related bug.
You may use sw* features (like coroutine, sockets) on fpm, but it won't boost up your cgi mode applications. On the opposite, hooks in sw* can even hurt performance.

Workloads are variant, for the heavy CPU loads, a multi-threaded server is better (while swow is running in single-thread in default). epoll vs select does not make an obvious difference.

As for heavy IO workloads (like for every request, you need to query mysql, redis, pgsql or do RPC), applications do not take much advantage by being multi-threaded, but really benefit from native IO facilities like epoll, kqueue, and IOCP, that's which sw* uses.
 
We will investigate the performance impact for fpm applications also, if that's a bug or should not be so slow, we will fix or optimize it.

(select(2) is the most original unix network facility which fpm uses, epoll(2) is the linux network facility with better performance, kqueue(2) is the bsd-flavor alternative (also used in macos), IOCP is the native windows asynchronous IO facility)

**Comment by dixyes** [comment]
So please provide the demo code, just echo hello world ?

**Comment by gilbertoalbino** [comment]
I wasn't using Swow with PHP-FPM.
What I meant is that after installing the Swow extension, my other PHP projects were somehow affected (maybe because the extension was loaded in PHP at runtime?).
So that before I could perform 30k req/sec. After installing this extension it affected my PHP installation as a whole so that it could just perform 10k req/sec.
After uninstalling this extension I could perform back 30K req/sec.
My projects are not simple "Hello world", they are full featured ones with MySQL, MongoDB, Redis that don't use any PHP Framework (like Laravel or Synfomy) and my infrastructure is fully optimized for High Availability.

What I "hello-world'ed" was your sample code, that couldn't get more thatn 10K req/sec.

I run my projects on a 16 core 128GB RAM physical machine on a 3500 read/ 2500/write SSD.

What I meant by my previous question was: "whats the point in using Swow if PHP/PHP-FPM themselves outperform it"?

I was just looking for a better alternative since PHP makes people spent a lot of money and I think it is not good to our planet.

Maybe my best solution is go for somewhat like C++ Drogon or Rust Axum, that really could deliver 100+ req/sec connected to MySQL, MongoDB and Redis all at once.

**Comment by dixyes** [comment]
Swow is not monkey patch... it hooks all you IO, but only asynchronous with coroutine.

For you usage without swow:
```text
cgi/cli got request
| - fork / create a thread to process it
    do some io
    do some cpu
    do some io
    return
```

For you usage with swow:
```text
swow create the (pro)reactor
cgi/cli got request
| - fork / create a thread to process it
    swap to (pro)reactor wait io done
    swap back from (pro)reactor
    do some cpu
    swap to (pro)reactor wait io done
    swap back from (pro)reactor
    return
```
You see, only overhead swow added

For the demo code:
```text
swow create the (pro)reactor
code make (pro)reactor wait for listen
the (pro)reactor got listen done
do some cpu
return

code make (pro)reactor wait for listen
the (pro)reactor got listen done
...
```
no better than multi-thread/process mode, only one thread is used

Real-world usage
```text
swow create the (pro)reactor
code1 make (pro)reactor wait for listen
the (pro)reactor got listen done
code1 process
code1 make (pro)reactor wait for annother connection
the (pro)reactor wait for two things, then it got another listen done
code2 process
code2 make (pro)reactor wait for annother connection
the (pro)reactor wait for three things, then it got code1 done
code1 continue
...
```

**Comment by twose** [comment]
You can just disable it if you are not using it. it's like a plane and a car racing for 100 meters, the plane can only win at a greater distance and it has a higher load capacity. Therefore, for short distances, it is not always advisable to use a plane as it spends most of its time on takeoff and landing.

**Comment by Eno-CN** [comment]
The reason why installing Swow extension affects other PHP projects is that you have enabled the Swow extension in the global configuration file (php.ini) of PHP. 

When PHP is running (either PHP-FPM or PHP-CLI), it automatically loads the extensions that are imported in the global configuration file. 

Therefore, you need to comment out the Swow extension in the global configuration file.
We recommend that you manually specify the loading of Swow when it is needed.

Of course, these instructions are also detailed in the installation document, which can be found at [Extension Installation](https://docs.toast.run/swow/en/install.html).

Also as shown in the following picture:
![image](https://github.com/swow/swow/assets/32012269/cd2df9a7-4689-49e0-b1c1-9df84409b7d2)
