### ISSUE TITLE
[question] 协程中代码没跑完就退出了 (运行is_dir无输出，返回错误码)

### ISSUE THREAD

**Issue by eogic** [swow/swow#195]
在协程中运行is_dir无输出，返回错误码

Coroutine::run( function() {
    var_dump(is_dir(__DIR__));
});

**Comment by sy-records** [comment]
主协程不能退出，退出就没了，建议读下文档https://docs.toast.run/swow-blog/chs/coroutine.html

**Comment by eogic** [comment]
> 主协程不能退出，退出就没了，建议读下文档https://docs.toast.run/swow-blog/chs/coroutine.html

感谢，才接触到swow，经常忘记这个机制
