### ISSUE TITLE
[bug] swow\Coroutine 里http请求无响应

### ISSUE THREAD

**Issue by cffycls** [swow/swow#206]
**Describe the bug / 问题描述**

Coroutine 里无响应

**To Reproduce / 如何复现**

```
<?php
declare(strict_types=1);
include_once './vendor/autoload.php';

use Swow\Psr7\Client\Client;
use Swow\Psr7\Psr7;

Swow\Coroutine::run(static function (): void {
    $client = new Client();
    $domain = 'www.baidu.com';
    $request = Psr7::createRequest(method: 'GET', uri: '/');
    $response = $client
        ->connect($domain, 80)
        ->sendRequest($request);

    echo 'Request', PHP_EOL, str_repeat('-', 40), PHP_EOL, Psr7::stringifyRequest($request);
    echo 'Response', PHP_EOL, str_repeat('-', 40), PHP_EOL, Psr7::stringifyResponse($response);

    var_dump(PHP_VERSION);
});
```

1. Do something first / 先做了什么
2. Then do another / 然后做了什么
3. Finally the software blew up / 它炸了

**Expected behavior / 正确的行为**

**Outputs / 程序输出**

**Runtime Environment / 运行环境**

OS:

```plain
fill here with your OS version / 在这填入你的OS信息
```
VER
Microsoft Windows [版本 10.0.22621.1848]

PHP: 
PHP 8.0.2 (cli) (built: Feb  3 2021 18:36:37) ( NTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies

Swow: 
Version => 1.3.1-b0661b59 ( NTS )

**Additional context / 补充说明**

****

**Comment by twose** [comment]
需要在底下 sleep 一段时间，或者使用其他更可靠的同步机制，详见：[Swow - 为什么协程一运行就退出了](https://docs.toast.run/swow-blog/chs/coroutine.html#%E5%8D%8F%E7%A8%8B%E7%9A%84%E8%A7%82%E6%B5%8B-%E6%8C%82%E8%B5%B7%E7%8A%B6%E6%80%81-%E4%B8%8A)

或者直接在顶层运行，在swow中一切都是协程环境

```php
declare(strict_types=1);
include_once './vendor/autoload.php';

use Swow\Psr7\Client\Client;
use Swow\Psr7\Psr7;

$client = new Client();
$domain = 'www.baidu.com';
$request = Psr7::createRequest(method: 'GET', uri: '/');
$response = $client
    ->connect($domain, 80)
    ->sendRequest($request);

echo 'Request', PHP_EOL, str_repeat('-', 40), PHP_EOL, Psr7::stringifyRequest($request);
echo 'Response', PHP_EOL, str_repeat('-', 40), PHP_EOL, Psr7::stringifyResponse($response);

var_dump(PHP_VERSION);
```

**Comment by cffycls** [comment]
感谢，好了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月10日(星期一) 下午2:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [swow/swow] [bug] swow\Coroutine 里http请求无响应 (Issue #206)





 
需要在底下 sleep 一段时间，或者使用其他更可靠的同步机制，详见：Swow - 为什么协程一运行就退出了
