### ISSUE TITLE
 不能给 swoole 添砖加瓦吗，非得搞个新的项目

### ISSUE THREAD

**Issue by axpwx** [swow/swow#215]

**Comment by dixyes** [comment]
别人我不知道 对我来说主要是xp问题， c++不太合我xp 看不懂c++ 写不明白c++ 所以就来写个c项目 （swoole坚定的使用c++ 我真顶不住啊）
搞个新项目也不是没给swoole添砖加瓦啊 swoole的multipart parser不就是用的这的修改版吗

**Comment by twose** [comment]
你怎么知道 Swoole 很多新特性 (近期的，包括但不限于 Xdebug 支持、PDO pgSQL 协程化）不是从 Swow 获得启发或者干脆就是同一批开发者同时贡献的呢？😂

Swow 本身一开始就是探索型的项目，为了打破有十多年历史的 Swoole  的能力边界而生，但 Swow 的核心开发者从来就没有脱离 Swoole 社区，也一直有在 Swoole 和核心开发者群里参与技术讨论，只是每个人因为现实工作的变化，精力的分配上没办法很好地协调。

此外，每一个人都可以是开源贡献者，都可以为任何开源项目添砖加瓦，楼主如果想支持 Swoole，但不具备给 swoole-src 提 PR 的能力，也可以给文档提 PR，如果文档也不行，也可以捐赠，捐不了太多，也可以去 [www.swoole.com](https://www.swoole.com/) 买点商业产品支持一下 Swoole 背后一边要用爱发电做开源一边要养家奶娃的团队，不管怎么样都比在 issue 里抱怨好，不是么？

**Comment by axpwx** [comment]
> 你怎么知道 Swoole 很多新特性 (近期的，包括但不限于 Xdebug 支持、PDO pgSQL 协程化）不是从 Swow 获得启发或者干脆就是同一批开发者同时贡献的呢？😂
> 
> Swow 本身一开始就是探索型的项目，为了打破有十多年历史的 Swoole 的能力边界而生，但 Swow 的核心开发者从来就没有脱离 Swoole 社区，也一直有在 Swoole 和核心开发者群里参与技术讨论，只是每个人因为现实工作的变化，精力的分配上没办法很好地协调。
> 
> 此外，每一个人都可以是开源贡献者，都可以为任何开源项目添砖加瓦，楼主如果想支持 Swoole，但不具备给 swoole-src 提 PR 的能力，也可以给文档提 PR，如果文档也不行，也可以捐赠，捐不了太多，也可以去 [www.swoole.com](https://www.swoole.com/) 买点商业产品支持一下 Swoole 背后一边要用爱发电做开源一边要养家奶娃的团队，不管怎么样都比在 issue 里抱怨好，不是么？

很遗憾被当成了抱怨，自 16 年开始一直是 swoole 的商业客户。
提这个 PR 只是单纯觉得现在PHP扩展周边的生态有点太乱了。
我本身没有任何恶意，向所有的开发者致敬，我们内部也有项目使用了你写的saber库，诚心感谢。

**Comment by twose** [comment]
因为标题带有明显的情绪输出，所以我只能这么理解了，如果标题能把「问题」和「个人观点」分离，那可能还有一些讨论的空间，讨论可以发在 discussion 而不是 issue。

无论如何，感谢支持，Swow 本身作为一个「驱动」而不是「框架」，对于上层使用者应当是无感的，尽管不是100%，但我们在努力做到这一点，就好像 cpython 和 pypy ，作为 Python 语言的两种实现，各自提供了差异化的价值，但又同属一个生态，它们的终极一定是满足不同开发者的需求，而不是混乱。

你所认为的混乱在我看来都来源于文档、用例或是最佳实践的匮乏，因此让人无法看清 Swow 提供的差异化价值点，这也是 Swow 项目运营到现在最大的缺陷，而这一问题又与「匮乏的外部贡献」和「核心开发者的个人精力不足」两个问题所捆绑，我们当前只能选择在企业内部孵化最佳实践案例，再反哺开源社区，但这一路径会比较漫长。

**Comment by jingjingxyk** [comment]
要是看过这张图：就不会这么问了
![image](https://github.com/swow/swow/assets/6836228/3086cc59-d75e-4801-994c-fbc376499469)


PPT 第23页 ： https://blog.jetbrains.com/wp-content/uploads/2022/06/20220113_jetbrains_cn_webinar_swoolenews.pdf
