### ISSUE TITLE
[discussion] 给Channel增加更多的异常类型

### ISSUE THREAD

**Issue by Dmcz** [swow/swow#222]
例如：
  Swow\ChannelTimeoutException  
  Swow\ChannelClosedException

**Comment by twose** [comment]
@Dmcz 现在统一用错误码判断 Errno::ETIMEDOUT, Errno::ECLOSED，存在什么问题？

如果使用异常分类，还有 Errno::CANCELED 这一情况，还涉及到其它类的异常要不要也这么做的问题，异常类型数量会非常爆炸。

**Comment by Dmcz** [comment]
> @Dmcz 现在统一用错误码判断 Errno::ETIMEDOUT, Errno::ECLOSED，存在什么问题？
> 
> 如果使用异常分类，还有 Errno::CANCELED 这一情况，还涉及到其它类的异常要不要也这么做的问题，异常类型数量会非常爆炸。

抱歉，没注意到`Errno`类。   我之前是通过`channel->isAvailable()`来区分异常，所以才想着应该加些类型。 谢谢啦
