### ISSUE TITLE
[discussion] 关于 Tcp 的重连

### ISSUE THREAD

**Issue by Dmcz** [swow/swow#227]
当 connect 失败时再次调用会抛出`Tcp connect init failed, reason: Software caused connection abort`异常
或者是我的使用方法不对，这里需要实例化一个新的socket?

简易代码，连接一个不存在的端口模拟失败
```php
<?php

$socket = new \Swow\Socket(\Swow\Socket::TYPE_TCP);

for ($i=0; $i < 6; $i++) { 
    try {
        $socket->connect("127.0.0.1", "1234");  
        break;
    } catch (\Swow\SocketException $e) {
        echo '(' . $e->getCode() . ')' . $e->getMessage() . PHP_EOL;
    }

    sleep(1);
}
```
```bash
// 输出结果
(-111)Socket connect failed, reason: Connection refused
(-103)Tcp connect init failed, reason: Software caused connection abort
(-111)Socket connect failed, reason: Connection refused
(-103)Tcp connect init failed, reason: Software caused connection abort
(-111)Socket connect failed, reason: Connection refused
(-103)Tcp connect init failed, reason: Software caused connection abort
```

**Comment by AuroraYolo** [comment]
注意：Socket connect failed, reason: Connection refused 提示连接被拒绝了。 connect方法里的端口号是int类型吧

**Comment by xywf221** [comment]
`Software caused connection abort` 这个报错应该是有问题。连接都没建立怎么会被中断

**Comment by Dmcz** [comment]
> 注意：Socket connect failed, reason: Connection refused 提示连接被拒绝了。 connect方法里的端口号是int类型吧

嗯，随便写的一个端口，模拟一下请求失败。这里如果时TCP的话，好像应该需要先关闭发送一个包，但是以前代码用php的socket直接再连好像没问题...

**Comment by AuroraYolo** [comment]
> `Software caused connection abort` 这个报错应该是有问题。连接都没建立怎么会被中断

我复用了他的代码，在mac一直提示
(-61)Socket connect failed, reason: Connection refused
(-22)Tcp connect init failed, reason: Invalid argument
(-22)Tcp connect init failed, reason: Invalid argument
(-22)Tcp connect init failed, reason: Invalid argument
(-22)Tcp connect init failed, reason: Invalid argument
(-22)Tcp connect init failed, reason: Invalid argument

**Comment by xywf221** [comment]
这个在linux是可以复现的
```
swow env: 

Swow

Status => enabled
Author => Swow Team
Link => https://github.com/swow/swow
Contact => Twosee <twosee@php.net>
Version => 1.3.1 ( NTS )
Built => Nov 15 2023 16:16:22
Context => boost-context
Scheduler => libuv-event
SSL => OpenSSL 3.0.11 19 Sep 2023
cURL => libcurl/8.4.0 OpenSSL/3.0.11 zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.11.0 nghttp2/1.57.0 librtmp/2.3 OpenLDAP/2.5.13
```

```
php env:
PHP 8.2.10 (cli) (built: Sep  5 2023 05:43:15) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.10, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.10, Copyright (c), by Zend Technologies
```

**Comment by twose** [comment]
Swow 提供的是底层最小能力，基本的 socket 知识，socket 不能重复 connect，在 PHP 封装中一个取巧的方法是你可以在 Socket close 后对 Socket 对象进行重新构造 `$socket->__construct()`。或者你自己封装一个代理对象，重新 new 一个 Socket 即可。

**Comment by twose** [comment]
像 cURL 之类的上层封装的重连，其实底层也是在重连时重新创建了一个操作系统的 socket

**Comment by Dmcz** [comment]
> Swow 提供的是底层最小能力，基本的 socket 知识，socket 不能重复 connect，在 PHP 封装中一个取巧的方法是你可以在 Socket close 后对 Socket 对象进行重新构造 `$socket->__construct()`。或者你自己封装一个代理对象，重新 new 一个 Socket 即可。

我以为只有连接成功后的才不能重新连...
旧代码中使用php socket重连的循环逻辑有bug所以没暴露出来问题...
