### ISSUE TITLE
configure error: invalid-pp-token

### ISSUE THREAD

**Issue by bestlake** [swow/swow#23]
checking for -single_module linker flag... In file included from <built-in>:365:
<command line>:2:17: warning: missing terminating '"' character [-Winvalid-pp-token]
#define CAT_VM \"zend\"

Configuration File (php.ini) Path: /Applications/MAMP/bin/php/php7.4.2/conf
Loaded Configuration File:         /Library/Application Support/appsolute/MAMP PRO/conf/php7.4.2.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)

**Comment by twose** [comment]
后面解决
