### ISSUE TITLE
[bug] windows环境swow1.4.0的二进制包与php8.2.13执行命令卡住

### ISSUE THREAD

**Issue by xiangjihan** [swow/swow#233]
执行以下三个命令会卡住：
composer selfupdate
composer update
composer config -g --list

**To Reproduce / 如何复现** 
1、从 https://windows.php.net/download 下载的php8.2.13的nts版的zip包
2、从 https://github.com/swow/swow/releases/tag/v1.4.0  下载的dll文件
3、配置好后执行上面的命令，比如composer config -g --list

![image](https://github.com/swow/swow/assets/3070542/fe809784-0e5b-4b11-905f-445ea6bb96b7)

为了防止因为因为配置问题出现问题，特意做了对比测试：
php8.2.8包 + swow1.3.1DLL文件，结果正常；
php8.2.13包 + swow1.3.1DLL文件，结果正常；
php8.2.8包 + swow1.4.0DLL文件，结果卡住；
php8.2.13包 + swow1.4.0DLL文件，结果卡住；
php8.2.8包在注释掉swow后，结果正常；
php8.2.13包在注释掉 swow后，结果正常；

程序输出
在命令行卡住，一直没有返回任何信息，也没有结束。

OS:
版本：Windows 10 专业工作站版
版本号：22H2
内部版本号：19045.3758

PHP
php-8.2.13-nts-Win32-vs16-x64.zip
SWOW
php_swow-php8.2-x64-nts-VS16.dll

补充说明
我看了异常日志没有记录到，貌似2个php版本与2个swow版本交叉测试后，总是swow1.4.0的版本出问题。
查看了进程的tcp选项没有没有建立连接
![image](https://github.com/swow/swow/assets/3070542/4ba91ba0-15a6-4204-bff0-b35db20e0cfb)

**Comment by xywf221** [comment]
compose加参数 -vvv看看日志输出

**Comment by xiangjihan** [comment]
> compose加参数 -vvv看看日志输出
出来的结果看不懂，哈哈
C:\Users\username>composer config -g --list -vvv
Loading config file C:/Users/username/AppData/Roaming/Composer/config.json
Loading config file C:/Users/username/AppData/Roaming/Composer/auth.json
Running 2.6.5 (2023-10-06 10:11:52) with PHP 8.2.13 on Windows NT / 10.0
Loading config file C:/Users/username/AppData/Roaming/Composer/config.json
Loading config file C:/Users/username/AppData/Roaming/Composer/auth.json
Reading C:/Users/username/AppData/Roaming/Composer/composer.json (C:\Users\username\AppData\Roaming\Composer\composer.json)
Loading config file C:/Users/username/AppData/Roaming/Composer/config.json
Loading config file C:/Users/username/AppData/Roaming/Composer/auth.json
Loading config file C:/Users/username/AppData/Roaming/Composer/composer.json (C:\Users\username\AppData\Roaming\Composer\composer.json)
Loading config file C:\Users\username\AppData\Roaming\Composer/auth.json
Reading C:\Users\username\AppData\Roaming\Composer/auth.json (C:\Users\username\AppData\Roaming\Composer\auth.json)
Checked CA file /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/certs/ca-certificates.crt does not exist or it is not a file.
Checked directory /etc/ssl/certs/ca-certificates.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/ca-bundle.pem does not exist or it is not a file.
Checked directory /etc/ssl/ca-bundle.pem does not exist or it is not a directory.
Checked CA file /usr/local/share/certs/ca-root-nss.crt does not exist or it is not a file.
Checked directory /usr/local/share/certs/ca-root-nss.crt does not exist or it is not a directory.
Checked CA file /usr/ssl/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /usr/ssl/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /opt/local/share/curl/curl-ca-bundle.crt does not exist or it is not a file.
Checked directory /opt/local/share/curl/curl-ca-bundle.crt does not exist or it is not a directory.
Checked CA file /usr/local/share/curl/curl-ca-bundle.crt does not exist or it is not a file.
Checked directory /usr/local/share/curl/curl-ca-bundle.crt does not exist or it is not a directory.
Checked CA file /usr/share/ssl/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /usr/share/ssl/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/cert.pem does not exist or it is not a file.
Checked directory /etc/ssl/cert.pem does not exist or it is not a directory.
Checked CA file /usr/local/etc/ssl/cert.pem does not exist or it is not a file.
Checked directory /usr/local/etc/ssl/cert.pem does not exist or it is not a directory.
Checked CA file /usr/local/etc/openssl/cert.pem does not exist or it is not a file.
Checked directory /usr/local/etc/openssl/cert.pem does not exist or it is not a directory.
Checked CA file /usr/local/etc/openssl@1.1/cert.pem does not exist or it is not a file.
Checked directory /usr/local/etc/openssl@1.1/cert.pem does not exist or it is not a directory.
Checked CA file /etc/pki/tls/certs does not exist or it is not a file.
Checked directory /etc/pki/tls/certs does not exist or it is not a directory.
Checked CA file /etc/ssl/certs does not exist or it is not a file.
Checked directory /etc/ssl/certs does not exist or it is not a directory.
Checked CA file /etc/ssl does not exist or it is not a file.
Checked directory /etc/ssl does not exist or it is not a directory.
Checked CA file /usr/local/share/certs does not exist or it is not a file.
Checked directory /usr/local/share/certs does not exist or it is not a directory.
Checked CA file /usr/ssl/certs does not exist or it is not a file.
Checked directory /usr/ssl/certs does not exist or it is not a directory.
Checked CA file /opt/local/share/curl does not exist or it is not a file.
Checked directory /opt/local/share/curl does not exist or it is not a directory.
Checked CA file /usr/local/share/curl does not exist or it is not a file.
Checked directory /usr/local/share/curl does not exist or it is not a directory.
Checked CA file /usr/share/ssl/certs does not exist or it is not a file.
Checked directory /usr/share/ssl/certs does not exist or it is not a directory.
Checked CA file /etc/ssl does not exist or it is not a file.
Checked directory /etc/ssl does not exist or it is not a directory.
Checked CA file /usr/local/etc/ssl does not exist or it is not a file.
Checked directory /usr/local/etc/ssl does not exist or it is not a directory.
Checked CA file /usr/local/etc/openssl does not exist or it is not a file.
Checked directory /usr/local/etc/openssl does not exist or it is not a directory.
Checked CA file /usr/local/etc/openssl@1.1 does not exist or it is not a file.
Checked directory /usr/local/etc/openssl@1.1 does not exist or it is not a directory.
Checked CA file C:\Users\username\AppData\Local\Temp\opeD56F.tmp: valid
Executing command (C:/Users/username/AppData/Roaming/Composer): git branch -a --no-color --no-abbrev -v

**Comment by twose** [comment]
从某天开始在 Windows 上构建的 Swow 的 cURL 就出现了迷之问题，由于我对 Windows 构建调试并不熟悉，@dixyes 也暂时没空调试  ，暂时无解，需要等下个版本我把整个 cURL 扩展迁移到 Swow 里才有可能解决。

**Comment by xiangjihan** [comment]
> 从某天开始在 Windows 上构建的 Swow 的 cURL 就出现了迷之问题，由于我对 Windows 构建调试并不熟悉，@dixyes 也暂时没空调试 ，暂时无解，需要等下个版本我把整个 cURL 扩展迁移到 Swow 里才有可能解决。

好的好的，那我先用1.3.1。

**Comment by xiangjihan** [comment]
从昨天运行完相关命令后感觉系统非常卡顿：windows 登录界面卡住十几分钟。随后检查发现在c:/user/username/AppData/Local/Temp/下，生成了几十万的sf_proc_XXXXX.out.lock文件，查询了相关资料好像是Composer进程创建的，怀疑是不是Composer相关的进程内存溢出造成了segfault的原因。

**Comment by dixyes** [comment]
调了半晚上发现PHP windows分发的php_curl.dll连接到的libcurl和他们分发的libcurl.a不匹配， 即使用了完全相同版本php也没救了

具体的：官方分发的curl 7.87.0 windows库和php 8.1 8.2近几个版本 8.3全部版本中链接到的curl 7.87.0内部abi不匹配，导致出现问题

只能通过port完整curl来解决了 预期下个发布版本解决

**Comment by devhaozi** [comment]
同样遇到了这个问题，导致 composer 卡住。

windows 11 23606.1
swow 1.4.1
php 8.2.14 nts

**Comment by dixyes** [comment]
1.5.0应该已经修了，试一下有无问题

**Comment by buexplain** [comment]
我这还会卡住，没有任何输出，希望多几个人试试，看看是不是只有我一个人遇到这个问题。
```shell
PS C:\buexplain\laravelTest> composer update --profile --verbose
^C终止批处理操作吗(Y/N)? Y
PS C:\buexplain\laravelTest> php --ri swow

Swow

Status => enabled
Author => Swow Team
Link => https://github.com/swow/swow
Contact => Twosee <twosee@php.net>
Version => 1.5.0-7d252473 ( NTS RELEASE )
Built => May  5 2024 13:50:37
Context => boost-context
Scheduler => libuv-event
DebugLog => enabled

Optional dependencies => Version Info
Sanitizers => none
SSL => OpenSSL 1.1.1q  5 Jul 2022 (built with OpenSSL 1.1.1s  1 Nov 2022)
cURL => libcurl/7.77.0 OpenSSL/1.1.1q zlib/1.2.12 WinIDN libssh2/1.10.0 nghttp2/1.46.0
PostgreSQL => libpq/11.4

Directive => Local Value => Master Value
swow.enable => On => On
swow.async_threads => 0 => 0
swow.async_file => On => On
swow.async_tty => On => On
curl.cainfo => no value => no value
PS C:\buexplain\laravelTest> php -v
PHP 8.1.10 (cli) (built: Aug 30 2022 18:08:04) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies
```
我用composer的源码跟进了一下，发现卡住的原因不是curl导致的，[具体卡住的代码](https://github.com/symfony/process/blob/3839e56b94dd1dbd13235d27504e66baf23faba0/Pipes/WindowsPipes.php#L65)如下：
```php
for ($i = 0;; ++$i) {
    foreach ($pipes as $pipe => $name) {
        $file = sprintf('%s\\sf_proc_%02X.%s', $tmpDir, $i, $name);

        if (!$h = fopen($file.'.lock', 'w')) {
            if (file_exists($file.'.lock')) {
                continue 2;
            }
            restore_error_handler();
            throw new RuntimeException('A temporary file could not be opened to write the process output: '.$lastError);
        }
        if (!flock($h, \LOCK_EX | \LOCK_NB)) {
            //这个 flock 函数失败后，跳出foreach，进入for循环，再次尝试，因为for循环是死循环，所以直接卡住
            continue 2;
        }
        if (isset($this->lockHandles[$pipe])) {
            flock($this->lockHandles[$pipe], \LOCK_UN);
            fclose($this->lockHandles[$pipe]);
        }
        $this->lockHandles[$pipe] = $h;

        if (!($h = fopen($file, 'w')) || !fclose($h) || !$h = fopen($file, 'r')) {
            flock($this->lockHandles[$pipe], \LOCK_UN);
            fclose($this->lockHandles[$pipe]);
            unset($this->lockHandles[$pipe]);
            continue 2;
        }
        $this->fileHandles[$pipe] = $h;
        $this->files[$pipe] = $file;
    }
    break;
}
```

**Comment by dixyes** [comment]
flock这个事就一言难尽了：windows上的flock是用LockFileEx模拟的，它的行为和unix flock有亿点点不同，文件锁在进程去世后（可能会）仍然存在，你可以试下清掉相关的所有文件缓存啥的（就是他试图锁的文件）然后再试一下

周末有空了我也测下看看lock没锁上会不会有别的原因

**Comment by buexplain** [comment]
> flock这个事就一言难尽了：windows上的flock是用LockFileEx模拟的，它的行为和unix flock有亿点点不同，文件锁在进程去世后（可能会）仍然存在，你可以试下清掉相关的所有文件缓存啥的（就是他试图锁的文件）然后再试一下
> 
> 周末有空了我也测下看看lock没锁上会不会有别的原因

我重启机器后，去临时目录删除干净相关的文件（sf_proc_*），composer还是会卡。
写代码单独测试flock，加上swow扩展会失败，去掉swow扩展会成功：
```php
<?php
$file = sprintf('%s\\testFlock.lock', sys_get_temp_dir());
if (is_file($file)) {
    unlink($file);
}
$h = fopen($file, 'w');
if (!$h) {
    die('打开文件失败');
}
var_dump(flock($h, LOCK_EX | LOCK_NB));
fclose($h);
unlink($file);
```

**Comment by dixyes** [comment]
flock这个原来是我的[丢人bug](https://github.com/swow/swow/commit/bf1515c237e6ffccca8c336c0e88192fb1aca006#diff-1deee33ca147acb4e0a32363b1d0d9096fcf87f1f3762ec6731d694c3773d224) 修了 等一个发版
之前curl会先搞寄composer，掩盖了这个flock的问题，多亏有个最小demo，才定位到问题。。。

**Comment by twose** [comment]
已在 v1.5.1 修复。

**Comment by dixyes** [comment]
@xiangjihan @devhaozi @buexplain 可以看看1.5.2的dll是否已经修复composer的问题

确认没问题再把这个issue关了

**Comment by buexplain** [comment]
> @xiangjihan @devhaozi @buexplain 可以看看1.5.2的dll是否已经修复composer的问题
> 
> 确认没问题再把这个issue关了

测试了一波，没问题了。
