### ISSUE TITLE
安装最新版本的扩展以后，compser不能用了，会直接卡住

### ISSUE THREAD

**Issue by Ezerbaby** [swow/swow#237]
安装最新版本的扩展以后，compser不能用了，会直接卡住
windows系统，swow1.4.1的ddl，php版本8.0.2
composer所有命令均无反应

**Comment by twose** [comment]
https://github.com/swow/swow/issues/233

PHP 官方分发的 Windows DLL 有问题导致 cURL 协程化不可用，下个版本尝试在 Swow 中兼容修复。

**Comment by twose** [comment]
v1.5.0 已解决。
