### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Kiniji0521** [swow/swow#247]
make: *** [swow.lo] Error 1
make: *** Waiting for unfinished jobs....
make: *** [src/swow_main.lo] Error 1
❌ Make failed

**Comment by Kiniji0521** [comment]
`[root@www 0512]# php vendor/bin/swow-builder
🔎 Please be patient while compiling in silent mode...
> cd /www/wwwroot/0512/vendor/swow/swow/ext && \
make -j2 > /dev/null
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/bin/sh /www/wwwroot/0512/vendor/swow/swow/ext/libtool --tag=CC --mode=compile cc -I. -I/www/wwwroot/0512/vendor/swow/swow/ext -I/www/wwwroot/0512/vendor/swow/swow/ext/include -I/www/wwwroot/0512/vendor/swow/swow/ext/main -I/www/wwwroot/0512/vendor/swow/swow/ext -I. -I./build Usage: php [options] [-f] <file> [--] [args...] php [options] -r <code> [--] [args...] php [options] [-B <begin_code>] -R <code> [-E <end_code>] [--] [args...] php [options] [-B <begin_code>] -F <file> [-E <end_code>] [--] [args...] php [options] -S <addr>:<port> [-t docroot] [router] php [options] -- [args...] php [options] -a -a Run as interactive shell (requires readline extension) -c <path>|<file> Look for php.ini file in this directory -n No configuration (ini) files will be used -d foo[=bar] Define INI entry foo with value 'bar' -e Generate extended information for debugger/profiler -f <file> Parse and execute <file>. -h This help -i PHP information -l Syntax check only (lint) -m Show compiled in modules -r <code> Run PHP <code> without using script tags <?..?> -B <begin_code> Run PHP <begin_code> before processing input lines -R <code> Run PHP <code> for every input line -F <file> Parse and execute <file> for every input line -E <end_code> Run PHP <end_code> after processing all input lines -H Hide any passed arguments from external tools. -S <addr>:<port> Run with built-in web server. -t <docroot> Specify document root <docroot> for built-in web server. -s Output HTML syntax highlighted source. -v Version number -w Output source with stripped comments and whitespace. -z <file> Load Zend extension <file>. args... Arguments passed to script. Use -- args when first argument starts with - or script is read from stdin --ini Show configuration file names --rf <name> Show information about function <name>. --rc <name> Show information about class <name>. --re <name> Show information about extension <name>. --rz <name> Show information about Zend extension <name>. --ri <name> Show configuration for extension <name>.  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -DHAVE_CONFIG_H -fvisibility=hidden -std=gnu99 -Wall -Wextra -Wstrict-prototypes -Wno-unused-parameter -Wno-assume  -D_GNU_SOURCE -DZEND_COMPILE_DL_EXT=1 -c /www/wwwroot/0512/vendor/swow/swow/ext/swow.c -o swow.lo  -MMD -MF swow.dep -MT swow.lo'
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/bin/sh /www/wwwroot/0512/vendor/swow/swow/ext/libtool --tag=CC --mode=compile cc -Isrc/ -I/www/wwwroot/0512/vendor/swow/swow/ext/src/ -I/www/wwwroot/0512/vendor/swow/swow/ext/include -I/www/wwwroot/0512/vendor/swow/swow/ext/main -I/www/wwwroot/0512/vendor/swow/swow/ext -I. -I./build Usage: php [options] [-f] <file> [--] [args...] php [options] -r <code> [--] [args...] php [options] [-B <begin_code>] -R <code> [-E <end_code>] [--] [args...] php [options] [-B <begin_code>] -F <file> [-E <end_code>] [--] [args...] php [options] -S <addr>:<port> [-t docroot] [router] php [options] -- [args...] php [options] -a -a Run as interactive shell (requires readline extension) -c <path>|<file> Look for php.ini file in this directory -n No configuration (ini) files will be used -d foo[=bar] Define INI entry foo with value 'bar' -e Generate extended information for debugger/profiler -f <file> Parse and execute <file>. -h This help -i PHP information -l Syntax check only (lint) -m Show compiled in modules -r <code> Run PHP <code> without using script tags <?..?> -B <begin_code> Run PHP <begin_code> before processing input lines -R <code> Run PHP <code> for every input line -F <file> Parse and execute <file> for every input line -E <end_code> Run PHP <end_code> after processing all input lines -H Hide any passed arguments from external tools. -S <addr>:<port> Run with built-in web server. -t <docroot> Specify document root <docroot> for built-in web server. -s Output HTML syntax highlighted source. -v Version number -w Output source with stripped comments and whitespace. -z <file> Load Zend extension <file>. args... Arguments passed to script. Use -- args when first argument starts with - or script is read from stdin --ini Show configuration file names --rf <name> Show information about function <name>. --rc <name> Show information about class <name>. --re <name> Show information about extension <name>. --rz <name> Show information about Zend extension <name>. --ri <name> Show configuration for extension <name>.  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -I/www/wwwroot/0512/vendor/swow/swow/ext/include -I/www/wwwroot/0512/vendor/swow/swow/ext/deps/ipv6-parse -I/www/wwwroot/0512/vendor/swow/swow/ext/include -I/www/wwwroot/0512/vendor/swow/swow/ext/deps/libcat/include -I/www/wwwroot/0512/vendor/swow/swow/ext/deps/libcat/deps/libuv/src -I/www/wwwroot/0512/vendor/swow/swow/ext/deps/libcat/deps/libuv/include -I/www/wwwroot/0512/vendor/swow/swow/ext/deps/libcat/deps/llhttp/include -I/www/wwwroot/0512/vendor/swow/swow/ext/deps/libcat/deps/multipart-parser-c -DHAVE_CONFIG_H -fvisibility=hidden -std=gnu99 -Wall -Wextra -Wstrict-prototypes -Wno-unused-parameter -Wno-assume  -D_GNU_SOURCE  -c src/swow_main.c -o src/swow_main.lo  -MMD -MF src/swow_main.dep -MT src/swow_main.lo'
make: *** [swow.lo] Error 1
make: *** Waiting for unfinished jobs....
make: *** [src/swow_main.lo] Error 1
❌ Make failed`

**Comment by Kiniji0521** [comment]
make: *** [swow.lo] Error 1
make: *** Waiting for unfinished jobs....
make: *** [src/swow_main.lo] Error 1
❌ Make failed

**Comment by Kiniji0521** [comment]
报错全发上来看不清楚，php8.3，CentOS 7.9.2009，宝塔面板安装失败尝试composer require swow/swow->php vendor/bin/swow-builder安装就这样

**Comment by Kiniji0521** [comment]
换了个系统用宝塔装上了1.4.1的，但是Hyperf要求1.5.1以上，手动编译还是报错

**Comment by Kiniji0521** [comment]
谁能给个编译好的，真的快崩溃了搞了一晚上

**Comment by twose** [comment]
你不贴报错怎么帮你看问题？

**Comment by twose** [comment]
可以去这里下载：

https://bin.dixyes.cn/flavors#s_os

**Comment by Kiniji0521** [comment]
```
[root@iZ7xv214ga7p4vm3annyn2Z 0512]# php vendor/bin/swow-builder --php-config=/www/server/php/83/bin/php --install
🔎 Please be patient while compiling in silent mode...
> cd /www/wwwroot/0512/vendor/swow/swow/ext && \
make -j2 > /dev/null
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/bin/sh /www/wwwroot/0512/vendor/swow/swow/ext/libtool --tag=CC --mode=compile cc -Isrc/ -I/www/wwwroot/0512/vendor/swow/swow/ext/src/ -I/www/wwwroot/0512/vendor/swow/swow/ext/include -I/www/wwwroot/0512/vendor/swow/swow/ext/main -I/www/wwwroot/0512/vendor/swow/swow/ext -I. -I./build Usage: php [options] [-f] <file> [--] [args...] php [options] -r <code> [--] [args...] php [options] [-B <begin_code>] -R <code> [-E <end_code>] [--] [args...] php [options] [-B <begin_code>] -F <file> [-E <end_code>] [--] [args...] php [options] -S <addr>:<port> [-t docroot] [router] php [options] -- [args...] php [options] -a -a Run as interactive shell (requires readline extension) -c <path>|<file> Look for php.ini file in this directory -n No configuration (ini) files will be used -d foo[=bar] Define INI entry foo with value 'bar' -e Generate extended information for debugger/profiler -f <file> Parse and execute <file>. -h This help -i PHP information -l Syntax check only (lint) -m Show compiled in modules -r <code> Run PHP <code> without using script tags <?..?> -B <begin_code> Run PHP <begin_code> before processing input lines -R <code> Run PHP <code> for every input line -F <file> Parse and execute <file> for every input line -E <end_code> Run PHP <end_code> after processing all input lines -H Hide any passed arguments from external tools. -S <addr>:<port> Run with built-in web server. -t <docroot> Specify document root <docroot> for built-in web server. -s Output HTML syntax highlighted source. -v Version number -w Output source with stripped comments and whitespace. -z <file> Load Zend extension <file>. args... Arguments passed to script. Use -- args when first argument starts with - or script is read from stdin --ini Show configuration file names --rf <name> Show information about function <name>. --rc <name> Show information about class <name>. --re <name> Show information about extension <name>. --rz <name> Show information about Zend extension <name>. --ri <name> Show configuration for extension <name>.  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -I/www/wwwroot/0512/vendor/swow/swow/ext/include -I/www/wwwroot/0512/vendor/swow/swow/ext/deps/ipv6-parse -I/www/wwwroot/0512/vendor/swow/swow/ext/include -I/www/wwwroot/0512/vendor/swow/swow/ext/deps/libcat/include -I/www/wwwroot/0512/vendor/swow/swow/ext/deps/libcat/deps/libuv/src -I/www/wwwroot/0512/vendor/swow/swow/ext/deps/libcat/deps/libuv/include -I/www/wwwroot/0512/vendor/swow/swow/ext/deps/libcat/deps/llhttp/include -I/www/wwwroot/0512/vendor/swow/swow/ext/deps/libcat/deps/multipart-parser-c -DHAVE_CONFIG_H -fvisibility=hidden -std=gnu99 -Wall -Wextra -Wstrict-prototypes -Wno-unused-parameter -Wno-assume  -D_GNU_SOURCE  -c src/swow_main.c -o src/swow_main.lo  -MMD -MF src/swow_main.dep -MT src/swow_main.lo'
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/bin/sh /www/wwwroot/0512/vendor/swow/swow/ext/libtool --tag=CC --mode=compile cc -I. -I/www/wwwroot/0512/vendor/swow/swow/ext -I/www/wwwroot/0512/vendor/swow/swow/ext/include -I/www/wwwroot/0512/vendor/swow/swow/ext/main -I/www/wwwroot/0512/vendor/swow/swow/ext -I. -I./build Usage: php [options] [-f] <file> [--] [args...] php [options] -r <code> [--] [args...] php [options] [-B <begin_code>] -R <code> [-E <end_code>] [--] [args...] php [options] [-B <begin_code>] -F <file> [-E <end_code>] [--] [args...] php [options] -S <addr>:<port> [-t docroot] [router] php [options] -- [args...] php [options] -a -a Run as interactive shell (requires readline extension) -c <path>|<file> Look for php.ini file in this directory -n No configuration (ini) files will be used -d foo[=bar] Define INI entry foo with value 'bar' -e Generate extended information for debugger/profiler -f <file> Parse and execute <file>. -h This help -i PHP information -l Syntax check only (lint) -m Show compiled in modules -r <code> Run PHP <code> without using script tags <?..?> -B <begin_code> Run PHP <begin_code> before processing input lines -R <code> Run PHP <code> for every input line -F <file> Parse and execute <file> for every input line -E <end_code> Run PHP <end_code> after processing all input lines -H Hide any passed arguments from external tools. -S <addr>:<port> Run with built-in web server. -t <docroot> Specify document root <docroot> for built-in web server. -s Output HTML syntax highlighted source. -v Version number -w Output source with stripped comments and whitespace. -z <file> Load Zend extension <file>. args... Arguments passed to script. Use -- args when first argument starts with - or script is read from stdin --ini Show configuration file names --rf <name> Show information about function <name>. --rc <name> Show information about class <name>. --re <name> Show information about extension <name>. --rz <name> Show information about Zend extension <name>. --ri <name> Show configuration for extension <name>.  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -DHAVE_CONFIG_H -fvisibility=hidden -std=gnu99 -Wall -Wextra -Wstrict-prototypes -Wno-unused-parameter -Wno-assume  -D_GNU_SOURCE -DZEND_COMPILE_DL_EXT=1 -c /www/wwwroot/0512/vendor/swow/swow/ext/swow.c -o swow.lo  -MMD -MF swow.dep -MT swow.lo'
make: *** [Makefile:236: src/swow_main.lo] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:227: swow.lo] Error 1
❌ Make failed
```

**Comment by Kiniji0521** [comment]
> 你不贴报错怎么帮忙看问题？

报错刚才发了，还有您给的那个链接我不会使用，抱歉，我不是php的开发人员，我只想要一个编译好的.so文件，如果链接里有那我自己再找找

**Comment by Kiniji0521** [comment]
> 你不贴报错怎么帮你看问题？

我看我发的报错信息是模糊的，引用这条信息的时候才可以看清楚

**Comment by dixyes** [comment]
> > 你不贴报错怎么帮你看问题？
> 
> 我看我发的报错信息是模糊的，引用这条信息的时候才可以看清楚

这样的 markdown文法会让你的报错变得没法看， 你拿\`\`\`包一下你的报错
像这样

    ```
    内容
    内容
    ```

**Comment by dixyes** [comment]
我给你把上面的内容包了下 这样就能看了

**Comment by dixyes** [comment]
有关markdown的更多信息可以看 https://learnxinyminutes.com/docs/zh-cn/markdown-cn/

至于swow这个构建出错，可能是builder写bug了，需要调查，至于上面的链接，那里可以下载一个包含了swow的php二进制，根据你的系统选择，具体如何选择有提示

**Comment by dixyes** [comment]
如何使用bin.dixyes.cn的flavors选择工具：

首先，选择操作系统，根据报错的路径来看，应该是个linux，那么我们选择linux
![屏幕截图 2024-05-16 145904](https://github.com/swow/swow/assets/11804369/73c24317-5eb5-49ec-b49f-bc53ef814ce3)

然后选择C库，假如你使用的是一个centos，根据centos图标选择上面的glibc，如果你不认得图标，把鼠标放到图标上有文字提示
![屏幕截图 2024-05-16 145931](https://github.com/swow/swow/assets/11804369/ab206605-9a1c-4725-9552-9ae80b04fb31)

然后选择架构，一般来说现在的云服务商提供的架构是x86_64，选择它
![屏幕截图 2024-05-16 145939](https://github.com/swow/swow/assets/11804369/a459bd8b-79a9-4d55-9c8c-111ce701ad73)

然后选择动态或静态，这里只有一个选项，选择动态
![屏幕截图 2024-05-16 145945](https://github.com/swow/swow/assets/11804369/0836389c-af8b-40d6-be3a-fcaa69ce4f9f)

然后选择风味，因为你要用swow，选择max-swow
![屏幕截图 2024-05-16 145953](https://github.com/swow/swow/assets/11804369/74c4c210-ae34-476f-ba9e-989718de48ce)

最后一步了，选择要用的php版本和CLI SAPI就可以下载了

![屏幕截图 2024-05-16 150005](https://github.com/swow/swow/assets/11804369/4d03fa52-7fee-420f-a61d-de00f0403b64)

![屏幕截图 2024-05-16 150016](https://github.com/swow/swow/assets/11804369/9cb5397a-34b4-4c5e-9649-68d8dc528250)

最后同意协议就可以下载了
![屏幕截图 2024-05-16 150024](https://github.com/swow/swow/assets/11804369/aa75f7ec-4262-4433-82f2-f493c9f4ac2c)

![屏幕截图 2024-05-16 150035](https://github.com/swow/swow/assets/11804369/7ea6153f-6ab6-4736-88ef-d8e8b0d392a3)

**Comment by dixyes** [comment]
我愣看了半天 终于发现了原因
```bash
php vendor/bin/swow-builder --php-config=/www/server/php/83/bin/php --install
```

这里使用是有问题的，你把php-config的路径配成php的路径了，这让configure和make很迷惑，

假如宝塔面板正确的安装了php的php-config命令，那么正确的用法是：

```bash
php vendor/bin/swow-builder --php-config=/www/server/php/83/bin/php-config --install
```

**Comment by Kiniji0521** [comment]
> 有关markdown的更多信息可以看 https://learnxinyminutes.com/docs/zh-cn/markdown-cn/
> 
> 至于swow这个构建出错，可能是builder写bug了，需要调查，至于上面的链接，那里可以下载一个包含了swow的php二进制，根据你的系统选择，具体如何选择有提示

好的，感谢耐心回复，get新技能了！我根据您的后续教程再研究一下！

**Comment by Kiniji0521** [comment]
> 我愣看了半天 终于发现了原因
> 
> ```shell
> php vendor/bin/swow-builder --php-config=/www/server/php/83/bin/php --install
> ```
> 
> 这里使用是有问题的，你把php-config的路径配成php的路径了，这让configure和make很迷惑，
> 
> 假如宝塔面板正确的安装了php的php-config命令，那么正确的用法是：
> 
> ```shell
> php vendor/bin/swow-builder --php-config=/www/server/php/83/bin/php-config --install
> ```

编译成功了，感谢，这里我一开始都没搞懂什么是php-config，我刚接触php开发。。抱歉给你们带来困扰。。。抱歉

**Comment by Kiniji0521** [comment]
> > 我愣看了半天 终于发现了原因
> > ```shell
> > php vendor/bin/swow-builder --php-config=/www/server/php/83/bin/php --install
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这里使用是有问题的，你把php-config的路径配成php的路径了，这让configure和make很迷惑，
> > 假如宝塔面板正确的安装了php的php-config命令，那么正确的用法是：
> > ```shell
> > php vendor/bin/swow-builder --php-config=/www/server/php/83/bin/php-config --install
> > ```
> 
> 编译成功了，感谢，这里我一开始都没搞懂什么是php-config，我刚接触php开发。。抱歉给你们带来困扰。。。抱歉

我一开始还以为是php.ini，后来还是报错，我就换成了php。。。

**Comment by Kiniji0521** [comment]
> 我愣看了半天 终于发现了原因
> 
> ```shell
> php vendor/bin/swow-builder --php-config=/www/server/php/83/bin/php --install
> ```
> 
> 这里使用是有问题的，你把php-config的路径配成php的路径了，这让configure和make很迷惑，
> 
> 假如宝塔面板正确的安装了php的php-config命令，那么正确的用法是：
> 
> ```shell
> php vendor/bin/swow-builder --php-config=/www/server/php/83/bin/php-config --install
> ```

我的这个bug issues需要删除掉吗？

**Comment by twose** [comment]
不用，解决就好，我 close 就行

**Comment by twose** [comment]
后续会考虑加上对应配置的检测，如检测配置的是不是正确的 php-config。

**Comment by lsitvoid** [comment]
有些小问题可以考虑问问AI；
如果无法解决就可以问问专业人士。
您遇到的错误提示表明在尝试使用 swow-builder 编译 Swow 扩展时，make 命令的调用出现了 shell 语法错误。错误消息 /bin/sh: -c: line 0: syntax error near unexpected token ('指出 shell 在解析-c参数提供的命令时遇到了一个不期望的(` 符号。
不过，从您提供的命令来看，并没有直接包含任何 ( 符号，所以这个错误可能是由 swow-builder 脚本内部生成的命令或者 make 文件的某一部分导致的。
要解决这个问题，您可以尝试以下步骤：
检查 swow-builder 脚本：
确认 swow-builder 脚本是否完整且没有损坏。
查看 Makefile：
如果 swow-builder 脚本没有问题，那么问题可能出在 Makefile 中。查看 /www/wwwroot/0512/vendor/swow/swow/ext/Makefile 或相关文件，查找任何可能导致此错误的行。
运行 make 命令手动：
尝试直接运行 make 命令，而不是通过 swow-builder 脚本。例如：
bash
cd /www/wwwroot/0512/vendor/swow/swow/ext  
make -j2
这样，您可以直接看到任何输出或错误，而无需通过 swow-builder 脚本。
检查 PHP 配置：
确保您指定的 --php-config 路径是正确的，并且指向了正确的 PHP 版本。
更新和安装依赖：
确保所有依赖都已正确安装和更新。特别是，如果 swow 依赖特定的库或工具，请确保它们都已安装。
查看文档和社区：
查看 Swow 的官方文档或社区论坛，看看是否有其他人报告了类似的问题，并找到了解决方案。
尝试使用不同的 shell：
有时，默认的 shell（如 /bin/sh）可能与某些命令或脚本不兼容。尝试使用其他 shell（如 /bin/bash）来运行 swow-builder 脚本。
检查权限：
确保您有足够的权限来编译和安装扩展。
使用 set -x 调试：
在 swow-builder 脚本或 Makefile 中添加 set -x 来开启调试，这样您可以看到实际执行的命令。
寻求帮助：
如果以上步骤都不能解决问题，您可以在 Swow 的社区、GitHub 仓库或其他相关论坛中寻求帮助。
