### ISSUE TITLE
[discussion] Swow\Psr7\Message\WebSocketFrame中没有设置public的opcode 和 data，fd的有什么深意吗？ 

### ISSUE THREAD

**Issue by xiangjihan** [swow/swow#251]
我在使用hyperf的swow内核做项目时，发现socketio-server在使用WebSocketFrame时，$frame->opcode、$frame->data、$frame->fd时，都会报属性不存在的错误，经过研究代码发现，除了opcode在C代码中并没有显式的设置为public ,其他两个变量并没有在PHP和C代码中设置。
是不是swow的设计思路是将这些额外属性，放置到上层框架中进行处理？而作为上层框架的Hyperf的engine-swow，并没有正确处理？

**Comment by twose** [comment]
Swow 都是用 `$frame->getXXX()` 方法获取，因为它直接从内存中的 WebSocket 帧数据中获取信息，而不会将其转换为 PHP 属性，这样不会有重复的内存占用。
用 `$frame->setXXX()` 方法改变属性值，也是会直接写到内存中的 WebSocket 帧数据中去，这样无需二次拼接帧数据就可以直接将帧对象作为数据发送出去。

至于 Hyperf 层面为什么有差异，得 @limingxinleo

**Comment by limingxinleo** [comment]
等我抽个时间搞搞，socketio-server 移植没做适配

**Comment by xiangjihan** [comment]
> Swow 都是用 `$frame->getXXX()` 方法获取，因为它直接从内存中的 WebSocket 帧数据中获取信息，而不会将其转换为 PHP 属性，这样不会有重复的内存占用。 用 `$frame->setXXX()` 方法改变属性值，也是会直接写到内存中的 WebSocket 帧数据中去，这样无需二次拼接帧数据就可以直接将帧对象作为数据发送出去。
> 
> 至于 Hyperf 层面为什么有差异，得 @limingxinleo

感谢两位大佬解惑。swow的frame中有opcode，但是没有data。我觉得很正常，因为使用了Playload获取就可以，但是我没找到fd，是不是fd没必要放在frame中。
