### ISSUE TITLE
[bug] win11下homestead环境中安装swow驱动报错

### ISSUE THREAD

**Issue by Risin9** [swow/swow#259]
【环境】
win11 homestead环境
【php -v】
PHP 8.2.13 (cli) (built: Nov 24 2023 08:46:50) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.13, Copyright (c), by Zend Technologies
【uname -a】
Linux homestead 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
【gcc --version】
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

【hyperf安装swow报错，通过composer安装，执行php vendor/bin/swow-builder命令】

以下是安装之后生成的**config.log**文件内容
**已更新上传对应文件**
[config.log](https://github.com/user-attachments/files/17365826/config.log)

**Comment by Risin9** [comment]
@dixyes 大佬有时间能帮忙看看什么问题不

**Comment by Risin9** [comment]
> @dixyes 大佬有时间能帮忙看看什么问题不

目前通过手动编译安装解决，希望大佬可以看下composer编译安装问题

**Comment by xywf221** [comment]
你这错误信息什么也看不到不如放个txt扔到上面

**Comment by dixyes** [comment]
首先不推荐在中国境内使用vagrant：hashicorp之前对中国禁售，没法保证之后会不会再一言不合又禁售，相关的服务支持和镜像源会很难找（如果你受雇于境外实体且在中国境外工作就可以放心使用了）基于这个原因，我不会考虑使用vagrant（及其之上的homestead），因此修复需要额外的调查时间。

从日志来看，问题是cc无法生成正常的可执行文件（cc或ld寄了）或目录内不可执行任何文件（可能使用了从宿主机到虚拟机的挂载？） 如果是cc问题，考虑重装gcc和binutils；如果是目录权限问题，这没有办法解决，你只能考虑不使用目录挂载。

至于代码实现，composer构建安装扩展的支持是 @twose 做的，让他修一下吧

**Comment by Risin9** [comment]
> 首先不推荐在中国境内使用vagrant：hashicorp之前对中国禁售，没法保证之后会不会再一言不合又禁售，相关的服务支持和镜像源会很难找（如果你受雇于境外实体且在中国境外工作就可以放心使用了）基于这个原因，我不会考虑使用vagrant（及其之上的homestead），因此修复需要额外的调查时间。
> 
> 从日志来看，问题是cc无法生成正常的可执行文件（cc或ld寄了）或目录内不可执行任何文件（可能使用了从宿主机到虚拟机的挂载？） 如果是cc问题，考虑重装gcc和binutils；如果是目录权限问题，这没有办法解决，你只能考虑不使用目录挂载。
> 
> 至于代码实现，composer构建安装扩展的支持是 @twose 做的，让他修一下吧

确实是从win目录挂载dao虚拟机目录的

**Comment by Risin9** [comment]
Homestead环境下，切换到非挂载目录下用composer方式可以安装成功

**Comment by dixyes** [comment]
> Homestead环境下，切换到非挂载目录下用composer方式可以安装成功

那就是vagrant问题了，建议卸了vagrant换其他虚拟机工具
