### ISSUE TITLE
WaitGroup的done方式似乎有个判断是错误的

### ISSUE THREAD

**Issue by amuluowin** [swow/swow#29]
![N`UHGZROUJZWA B YA)SDD2](https://user-images.githubusercontent.com/19545561/97444868-93630c80-1967-11eb-84f4-292a554099d4.png)

这个判断会导致在协程内`done`的时候报错，这个判断是否不需要。
如果需要的话，只能是`new Coroutine`在`resume()`后执行`done`，此时协程已经结束。

**Comment by twose** [comment]
已在上游修复, 下次同步依赖时也会在Swow中修复

**Comment by twose** [comment]
Fixed via 3658d73
