### ISSUE TITLE
README中路径问题

### ISSUE THREAD

**Issue by jobinli** [swow/swow#37]
> 使用此方式安装时，最后一步程序会提示输入密码以使用root权限安装到系统，你可以选择不输入，安装程序仍会提供类似于以下的运行命令：
>
> /usr/bin/env php -n -d extension=/path/to/vendor/swow/swow/ext/.build/swow.so --ri swow
>
> 即扩展的so文件输出到了你项目的vendor目录下，相当于扩展也拥有了版本控制，你可以为你的每个项目指定不同版本的Swow，而无需全局使用同一个扩展so。

实际 `swow.so` 路径，是否为 `/path/to/vendor/swow/swow/modules/swow.so`。并未看到有 `.build` 文件夹
![image](https://user-images.githubusercontent.com/59111601/101429364-bce75e80-393d-11eb-8314-7e642b9229db.png)

**Comment by cexll** [comment]
直接 -dextension=swow

**Comment by jobinli** [comment]
> 直接 -dextension=swow

并不是加载问题，而是文档描述的路径有误。我采用了 `-d` 指定加载路径的形式，没有全局安装。
