### ISSUE TITLE
Windows version extension

### ISSUE THREAD

**Issue by hailingr** [swow/swow#38]
windows上如果编译安装？

**Comment by dixyes** [comment]
config.w32 yet not implemented, if you need windows version, try compile sources, and link them all manually.

config.w32还没整好，如果你想用就先手动编译链接一下

**Comment by hawind** [comment]
24天没有更新了，希望坚持下去，很期待win版本啊

**Comment by dixyes** [comment]
花了点时间整了下： 可以试试 https://github.com/dixyes/swow/tree/windows

目前还是编译不过，需要同步一下libcat或者手动打下这个补丁

```patch
diff --git a/ext/deps/libcat/src/cat_fs.c b/ext/deps/libcat/src/cat_fs.c
index ee2709f..8d9a21b 100644
--- a/ext/deps/libcat/src/cat_fs.c
+++ b/ext/deps/libcat/src/cat_fs.c
@@ -118,9 +118,6 @@ CAT_API int cat_fs_open(const char *path, int flags, ...)

 CAT_API off_t cat_lseek(int fd, off_t offset, int whence)
 {
-#ifdef CAT_OS_WIN
-#define lseek _lseek64
-#endif
     return lseek(fd, offset, whence);
 }
```

[php_swow_php800_vs16_nts_ndbg_aab15b155.dll.zip](https://github.com/swow/swow/files/5755174/php_swow_php800_vs16_nts_ndbg_aab15b155.dll.zip)

**Comment by hawind** [comment]
> 花了点时间整了下： 可以试试 https://github.com/dixyes/swow/tree/windows
> 
> 目前还是编译不过，需要同步一下libcat或者手动打下这个补丁
> 
> ```diff
> diff --git a/ext/deps/libcat/src/cat_fs.c b/ext/deps/libcat/src/cat_fs.c
> index ee2709f..8d9a21b 100644
> --- a/ext/deps/libcat/src/cat_fs.c
> +++ b/ext/deps/libcat/src/cat_fs.c
> @@ -118,9 +118,6 @@ CAT_API int cat_fs_open(const char *path, int flags, ...)
> 
>  CAT_API off_t cat_lseek(int fd, off_t offset, int whence)
>  {
> -#ifdef CAT_OS_WIN
> -#define lseek _lseek64
> -#endif
>      return lseek(fd, offset, whence);
>  }
> ```
> 
> [php_swow_php800_vs16_nts_ndbg_aab15b155.dll.zip](https://github.com/swow/swow/files/5755174/php_swow_php800_vs16_nts_ndbg_aab15b155.dll.zip)

使用了，确实可以，感谢！

**Comment by twose** [comment]
Windows version is now available

**Comment by gouchaoer** [comment]
有dll么，我有一些php写的windows下的脚本工具，用php的win绿色版（本来打算用go写无依赖，但是写的太慢了也不好更新），想尝个鲜

**Comment by dixyes** [comment]
> 
> 
> 有dll么，我有一些php写的windows下的脚本工具，用php的win绿色版（本来打算用go写无依赖，但是写的太慢了也不好更新），想尝个鲜

ci整好了，但是目前还没有发布。 如果你偷懒的话，fork这个仓库，开启action，然后建个tag，gh ci会自动构建dll并且上传到releases里
