### ISSUE TITLE
请问多久提交到rfc啊，期待中

### ISSUE THREAD

**Issue by thinker-gao** [swow/swow#40]
请问多久提交到rfc啊，期待中

**Comment by diankemao** [comment]
我也想知道啥时候发版

**Comment by twose** [comment]
感谢关注，RFC还在酝酿中，Swow是一个庞大的系统，协程只是其中很小的一部分，因此涉及到的设计细节会很多，RFC书写难度也很大，并非一日之功，敬请期待。
