### ISSUE TITLE
这个项目是干啥的跟swoole有什么不同,文档什么时候完善,预计什么时候可用？

### ISSUE THREAD

**Issue by fly2006zhao** [swow/swow#51]

**Comment by dixyes** [comment]
see README: https://github.com/swow/swow/blob/develop/README-CN.md

见README： https://github.com/swow/swow/blob/develop/README-CN.md

btw, please put your questions in content, issue title should be short and clear.

顺便说下，请把具体问题放在正文部分，issue标题要简介明确
