### ISSUE TITLE
关于stream_set_blocking阻塞疑惑

### ISSUE THREAD

**Issue by NathanFreeman** [swow/swow#58]
你好，关于stream_set_blocking设置为非阻塞之后还是阻塞的问题，我看了一下swow的代码，发现：

    static int swow_stream_set_option(php_stream *stream, int option, int value, void *ptrparam) {
        // 省略
        /* always blocked */
        return PHP_STREAM_OPTION_RETURN_OK;  这里是没有操作的
    }

我又看了一下php8这部分的源码，这里是：
    oldmode = sock->is_blocked;
    if (SUCCESS == php_set_sock_blocking(sock->socket, value)) {
    sock->is_blocked = value;
    return oldmode;
    }
    return PHP_STREAM_OPTION_RETURN_ERR;

php_set_sock_blocking 也是直接执行fcntl修改套接字的属性，请问这里为啥不能直接copy过去呢？

**Comment by twose** [comment]
这个问题解释起来比较复杂，最新代码在ci分支可以看看。
协程socket完美模拟了阻塞socket的行为，但非阻塞行为支持还在完善中。

**Comment by NathanFreeman** [comment]
> 
> 
> 这个问题解释起来比较复杂，最新代码在ci分支可以看看。
> 协程socket完美模拟了阻塞socket的行为，但非阻塞行为支持还在完善中。

看的有点吃力，本以为基本看懂了swoole，看swow应该可以的，我还是太年轻了。

**Comment by twose** [comment]
已支持non-blocking和SSL
