### ISSUE TITLE
Mac编译时提示waring,执行php -m提示协程与操作opcode部分扩展不兼容

### ISSUE THREAD

**Issue by AuroraYolo** [swow/swow#60]
PHP：7.4.7
系统:Mac os Big Sur 11.2.3
编译提示的错误信息:

....
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
src/swow_fs.c:378:57: warning: missing field 'error' initializer [-Wmissing-field-initializers]
    struct _swow_fs_open_s data = {-1, NULL, flags, 0666};
                                                        ^
1 warning generated.

✅ Make complete

...

执行php-m提示的错误信息:
PHP Fatal error:  Coroutine module is incompatible with some extensions that setup exit user opcode handler in Unknown on line 0

Fatal error: Coroutine module is incompatible with some extensions that setup exit user opcode handler in Unknown on line 0

**Comment by twose** [comment]
不能与不兼容的扩展同时开启，请在ini中关闭可能冲突的扩展。
