### ISSUE TITLE
什么时候准备出一个think-swow

### ISSUE THREAD

**Issue by 54huige** [swow/swow#62]
例如像think-swoole一样，因为这个在thinkphp6中使用多应用时无法正常路由，听说swow很强，希望以后能用上 think-swow 提供 windows和linux的高性能接口服务

**Comment by to2false** [comment]
这个不应该是去tp下面问适配think-swow吗

**Comment by fywtat** [comment]
swow都还远着呢，就想着think-swow 为啥不说laravel-swow
