### ISSUE TITLE
[discussion] (作为不熟悉c和c++的人,可以从哪里帮助swow?)

### ISSUE THREAD

**Issue by AuroraYolo** [swow/swow#64]
或者说不参与内核开发，在哪里可以帮忙开发swow？ # @dixyes @twose

**Comment by twose** [comment]
修复错别字、修复错误的代码格式、文档编写、文档翻译、或是参与[PHP部分的代码](https://github.com/swow/swow/tree/develop/lib/src/Swow)开发都是可以的
