### ISSUE TITLE
[discussion] (建议废弃lib下面的内容，这些完全让php开发者自己去实现。专心维护ext的稳定性、性能、兼容性)

### ISSUE THREAD

**Issue by lizhichao** [swow/swow#79]
这是只是一个建议，要长远的支持下去，做的太多耗费的精力太多了，做的太多也容易产生更多的bug，即使很努力 也容易会给人一种很不稳定的影响。 建议尽量的少，保持非常好的灵活、稳定性、兼容性（类似workerman php5.3+都能用 ，并不是说需要支持5.x 只是表达着个库|扩展不挑环境 适应性很强）

**Comment by limingxinleo** [comment]
lib下的内容，就是由其他phper来贡献代码的

**Comment by lizhichao** [comment]
> lib下的内容，就是由其他phper来贡献代码的

那也不应该放在一起吧，lib一看好像是底层公用库的感觉。或者换个名字叫demo，example 更合适

**Comment by twose** [comment]
lib下的内容，都是本应该由C扩展实现的，但有些模块对于性能并不敏感，因此使用PHP开发可以很好地提升开发效率，包括PHP内核未来也会考虑使用PHP实现一些内置函数而不是C，你可以看一下nodejs的源码，lib目录就是js文件。
lib提供的东西都是目前swoole-src中已有的内容，都是为了满足大部分开发者的核心需求。而转而让社区自己编写核心功能库，难免会出现良莠不齐的情况，开发者无法开箱即用，还需要自己甄选，加大了入门门槛。
社区可以贡献一些核心功能到Swow的lib库，经过严格的review合并到Swow中，让更多开发者受益。
