### ISSUE TITLE
[discussion] (单进程模型的问题)

### ISSUE THREAD

**Issue by cceessff** [swow/swow#82]
swow现在是不是和node一样的单进程模型，无法对多核cpu充分利用，如果是这样有什么好的解决办法吗？

**Comment by limingxinleo** [comment]
基于docker跑多个进程

**Comment by cceessff** [comment]
Duplicate of #

> 基于docker跑多个进程

如果是这种办法，我直接多配置几个服务，监听不同的端口就行了

**Comment by twose** [comment]
Swow、Swoole、nodejs都是单线程多进程，而不是单进程模型。
目前Swow还不支持多进程是因为还没有将libcat的多进程模块引入到PHP扩展层，马上就有了，再等等。
基于docker的方案也是可以的。

**Comment by codingheping** [comment]
go go起来啊。
