### ISSUE TITLE
[bug] (使用 ab 命令测试时 php进程自动结束)

### ISSUE THREAD

**Issue by codedragen** [swow/swow#84]
**Describe the bug / 问题描述**
使用 ab 命令进行测试，ab命令输出： **apr_socket_recv: 远程主机强迫关闭了一个现有的连接。   (730054)**，并且php进程自动结束

**To Reproduce / 如何复现**

1. php index.php
2. .\ab.exe -n 1000 -c 60   http://127.0.0.1:8088/

**Expected behavior / 正确的行为**

ab命令不报错，php进程不自动结束

**Outputs / 程序输出**

php进程结束无任何输出

**Runtime Environment / 运行环境**

OS:

```plain
Caption=Microsoft Windows 10 家庭中文版
CSDVersion=
OSArchitecture=64 位
OSLanguage=2052
TotalVisibleMemorySize=16571704
Version=10.0.19042

Architecture=9
Caption=Intel64 Family 6 Model 140 Stepping 1
Name=11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
NumberOfCores=4
NumberOfLogicalProcessors=8
```

PHP: 
PHP 7.4.8 (cli) (built: Jul  9 2020 11:30:33) ( NTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.0, Copyright (c) 2002-2019, by Derick Rethans
**Additional context / 补充说明**

使用代码
```php
<?php
require 'vendor/autoload.php';

use Swow\Coroutine;
use Swow\Http\Exception as HttpException;
use const Swow\Errno\EMFILE;
use const Swow\Errno\ENFILE;
use const Swow\Errno\ENOMEM;

ini_set('memory_limit', '1G');
$server = new Swow\Http\Server();
$server->bind("127.0.0.1", 8088)->listen();
while (true) {
    try {
        $session = $server->acceptSession();
        Coroutine::run(function (Swow\Http\Server\Session $session)  {
            try{
                while (true) {
                    try {
                        $request = null;
                        $request = $session->recvHttpRequest();
                        switch ($request->getPath()) {
                            case '/':
                            {
                                $session->respond("hello world");
                                break;
                            }
                            default:
                            {
                                $session->error(404);
                            }
                        }
                    } catch (HttpException $exception ) {
                        $session->error($exception->getCode(), $exception->getMessage());
                    }
                    if (!$request || !$request->getKeepAlive()) {
                        //echo "break\n";
                        break;
                    }
                }
            }catch (Exception $exception){
                echo  $exception->getMessage();
            } finally {
                $session->close();
            }
        },$session);
    } catch (Exception $exception) {
        if (in_array($exception->getCode(), [EMFILE, ENFILE, ENOMEM], true)) {
            sleep(1);
        } else {
            break;
        }
    }
}
```

**Comment by dixyes** [comment]
在PHP 7.4.8和7.4.20的nts x64官方发布下和Xdebug3.0.4均未复现

PHP 7.4.8+Xdebug2.9.0下复现， 推测为xdebug问题，建议更新xdebug版本

p.s. 尽管3.0.4看起来能用，但现在并不能保证能与xdebug完全兼容，同时用仍然可能会有其他问题，可以考虑使用sdb

**Comment by codedragen** [comment]
> 在PHP 7.4.8和7.4.20的nts x64官方发布下和Xdebug3.0.4均未复现
> 
> PHP 7.4.8+Xdebug2.9.0下复现， 推测为xdebug问题，建议更新xdebug版本
> 
> p.s. 尽管3.0.4看起来能用，但现在并不能保证能与xdebug完全兼容，同时用仍然可能会有其他问题，可以考虑使用sdb

谢谢，配置中注释掉xdebug后确实没有再出现问题。可以肯定是xdebug的问题了。另外问一下sdb是什么？

**Comment by twose** [comment]
![image](https://user-images.githubusercontent.com/25978241/127827424-02df1faa-fcce-440b-9e91-91b9c72f2ebb.png)

https://wiki.s-wow.com/#/zh-cn/tools/sdb

但是暂时不能和IDE联合使用，后续会增加支持

**Comment by codedragen** [comment]
> ![image](https://user-images.githubusercontent.com/25978241/127827424-02df1faa-fcce-440b-9e91-91b9c72f2ebb.png)
> 
> https://wiki.s-wow.com/#/zh-cn/tools/sdb
> 
> 但是暂时不能和IDE联合使用，后续会增加支持

感谢大佬亲自回复
