### ISSUE TITLE
[discussion] 能否把这个拓展无缝替换swoole 

### ISSUE THREAD

**Issue by askme-gpt** [swow/swow#85]
能否不改变目前用到swoole项目代码的情况下直接加swow拓展行不行？我们目前有几个遗留项目使用的easy-swoole框架，其他是golang和laravel项目，我的点奥配置不好，用了两年的电脑丢掉挺可惜。因此想直接在windows下面不用docker,wsl,虚拟机，cygwin的情况下，只要满足开发需求即可，不需要实际linux的效果，因为最终测试和压测都是在部署环境进行。

**Comment by dixyes** [comment]
1. swow和swoole提供了相同的设施，因而是相互冲突的，他们不能一同使用
2. swow和swoole的api接口有亿点点不同，如果你的框架提供了高级抽象摸平了这种不同，那他们是可以交换的，具体替换方法请参考框架使用文档
3. 尽管swow支持原生windows php，但具体到像路径名（/usr/bin/xxx或者C:\Windows\System32\xxx）或者unix socket/windows pipe这样的区别，windows原生php是没法提供相同的抽象的。

个人建议使用swoole官方提供的cygwin包，这不需要你手动构建，在cygwin shell下使用体验也接近原生unix
