### ISSUE TITLE
[discussion] 上线时间线整一个怎么样？还有亿点点疑问。

### ISSUE THREAD

**Issue by leihenshang** [swow/swow#88]
1. 众所周知现在 swoole 对于除mysql/postgreSQL外的其他数据库 mongoDB\MsSqlserver无法支持协程,swow到时候要使用什么样的机制和方式来解决类似的问题，还是说任然需要厂商推动？

真的只有一点点

**Comment by twose** [comment]
目前比较通用的是结合task-worker的模式，即投递阻塞任务给task进程池，会多一层IPC的开销，性能会比协程差一点。
最好的方式自然是原生驱动的，pgSQL是官方驱动就有异步化API支持，这个后续Swow也会支持的，但是MongoDB是线程池的模式，官方都不支持异步，这个就比较困难了，但是我们正好也在计划支持中，还处于研究阶段。MSSQL优先级可能会低一点，可以通过task-worker解决。
