### ISSUE TITLE
[discussion] Starting a new project, should use Swow or Swoole?

### ISSUE THREAD

**Issue by kspaced** [swow/swow#91]
Hello,

We're starting a new project that will include a number of microservices with critical performance requirements. Some HTTP servers and some WebSockets servers.

The question is, should we use Swow or Swoole since we have limited hardware resources and want to make the most of what we have and performance is of essence, and what should be the use cases for each of Swow and Swoole?

**Comment by kspaced** [comment]
@twose Is it possible to have input here :) ?

**Comment by AuroraYolo** [comment]
Yes, I think swow can be used,https://github.com/SerendipitySwow/Serendipity-job,
https://github.com/swow-cloud/music-server. Websocket demo

**Comment by twose** [comment]
@kspaced
I'm busy with other work at the moment.
But I am willing to write a detailed reply later :)
