### ISSUE TITLE
windows编译（composer）提示 “Not supported on Windows temporarily”

### ISSUE THREAD

**Issue by gxdyxh** [swow/swow#99]
RT：windows编译（composer）提示 “Not supported on Windows temporarily”
![图片](https://user-images.githubusercontent.com/33820361/147026154-b7518be1-bdde-4473-991b-ed319b84ef9e.png)

**Comment by twose** [comment]
Windows直接使用官方发布的dll就行了 https://github.com/swow/swow/releases
这个只是说Linux下的构建脚本不支持Windows，因为Windows需要通过其他方式构建。
